### ISSUE TITLE
Remove "scan" machines from MonkeyZoo

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1023]
**Is your feature request related to a problem? Please describe.**
Remove `scan` machines from monkeyZoo. The same behavior of the "safe" machine can be achieved if we removed vulnerable credentials from the config.

**Describe the solution you'd like**
Remove `scan` machines from the terraform scripts
Remove `scan` images from GCP
Remove `scan` machines from docs (`fullDocs.md`)

**Describe alternatives you've considered**
Keeping those machines

**Comment by mssalvatore** [comment]
This was completed, though I'm not sure exactly when.
