### ISSUE TITLE
Make BB more scalable

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1038]
**Is your feature request related to a problem? Please describe.**
BB test turns on a bunch of machines at once, which triggers quotas and raises other issues.

We should find a scalable way to add BB tests and refactor the next chance we get.

**Describe the solution you'd like**

We should turn on/off machines for relevant tests, not everything at once.

**Comment by mssalvatore** [comment]
I contacted Google and our quota has been raised from 24 to 32, reducing the urgency of this issue.

**Comment by VakarisZ** [comment]
Since this issue is less relevant I'll close it. We could probably save some money if we only ran one test at a time, but lets leave it for another issue
