### ISSUE TITLE
Refactor PyInstaller Bootloader

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1039]
Infection Monkey's custom [PyInstaller bootloader](https://github.com/guardicore/pyinstaller) has a number of potential memory corruption issues that, in the future, could result in more bugs similar to #1030. Furthermore, it can be refactored to improve code quality and make defects easier to find.
Refactor the PyInstaller bootloader, resolving memory corruption issues along the way.

See also:
https://github.com/guardicore/pyinstaller/pull/8
https://github.com/guardicore/pyinstaller/pull/9

**Comment by VakarisZ** [comment]
Fixed in https://github.com/guardicore/pyinstaller/pull/9 ?

**Comment by mssalvatore** [comment]
> Fixed in [guardicore/pyinstaller#9](https://github.com/guardicore/pyinstaller/pull/9) ?

No, this is a broader cleanup refactoring effort than that PR.

**Comment by mssalvatore** [comment]
The bootloader was removed in https://github.com/guardicore/monkey/issues/1676
