### ISSUE TITLE
Upgrade PyInstaller to the latest version

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1040]
Upgrade [our fork of PyInstaller](https://github.com/guardicore/pyinstaller) to the latest version. Test that monkey agent binaries can still be built and the bootloaders run without issue.

See https://github.com/guardicore/pyinstaller/commits/python_dll_fix

**Comment by VakarisZ** [comment]
Fixed in https://github.com/guardicore/pyinstaller/pull/10
