### ISSUE TITLE
Make system info collection code more modular.

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1043]
**Is your feature request related to a problem? Please describe.**
System info collector code is tightly coupled and the main problem with that is once a single info collector crashes, all other collectors follow.

**Describe the solution you'd like**
When one collector crashes, others should continue with info collection if possible

**Comment by mssalvatore** [comment]
System info collectors have been replaced with Credentials Collectors. This issue should be resolved by the agent-refactor project.
