### ISSUE TITLE
AWS key setup UX improvement

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1053]
**Is your feature request related to a problem? Please describe.**
If you setup AWS keys for ScoutSuite, you need to click a chain of "back" or "run on the island" in the info prompt to go to the initial run page again:
![image](https://user-images.githubusercontent.com/36815064/112437994-42a5e300-8d50-11eb-9192-afe4b9581cca.png)

**Describe the solution you'd like**
Instead, if keys are validated successfully, user should be moved to the initial monkey run window with the same info message. The link on the info message should start the monkey on the island.

This will save additional clicks for users and guide them better through the process.

**Comment by mssalvatore** [comment]
ScoutSuite was removed in #1669
