### ISSUE TITLE
Unable to download .deb file

### ISSUE THREAD

**Issue by rorobig** [guardicore/monkey#1073]
## Describe the bug
After filling in the form on the infection monkey website, i don't receive an email with the download link to my installer file (infection-monkey.deb)
## To Reproduce
Steps to reproduce the behaviour:
1. Go to the infection monkey website
2. Sign up to receive installer via email
3. No email

## Expected behaviour
A description of what you expected to happen.
Download link emailed to me

## Machine version (please complete the following information):
 - OS:Linux

**Comment by mssalvatore** [comment]
@rorobig Please check your spam folder to see if it ended up in there.

We're hearing this a lot lately. I'll look into it on our side.

**Comment by rorobig** [comment]
Thanks for the response.
I checked my spam folder and used other email addresses still no luck.

**Comment by VakarisZ** [comment]
@rorobig For now use: https://guardicore-infectionmonkey.s3.amazonaws.com/Files/1.9.0/Regular/monkey-island-debian.deb

**Comment by rorobig** [comment]
Thank you!

**Comment by VakarisZ** [comment]
Let's keep open until next release fixes this

**Comment by mssalvatore** [comment]
@rorobig We've just released Infection Monkey v1.10.0 and I believe the download e-mails are fixed. Would you mind trying once again to fill in the form and download the latest infection monkey?

**Comment by rorobig** [comment]
Fixed! I can download the file now with no issue.
Thanks for the fast response.
