### ISSUE TITLE
AppImage jenkins script

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1103]
Create a jenkins script to build AppImage binary. Make sure to follow cleanup guidelines set in the “Low level workflow”. Make sure this build triggers builds of agent binaries first. 

- [x] Create a jenkins script to build AppImage binary(verify that only the most recent 2 artifacts are stored in jenkins). (0d) - @mssalvatore

**Comment by mssalvatore** [comment]
Waiting on https://github.com/guardicore/labs/pull/233
