### ISSUE TITLE
Rewrite PBAs to avoid shell=True

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#1118]
**Is your feature request related to a problem? Please describe.**
All PBAs currently use `shell=True` while running the commands with `subprocess`. While this isn't a concern right now, it should be changed to avoid problems in the future. Simply removing `shell=True` and splitting the commands isn't an option due to the complexity.

**Describe the solution you'd like**
Create shell scripts for all PBAs and remove the existing framework around it. 
EDIT: See #1679

**Describe alternatives you've considered**
Most of the steps can be performed in python using existing libraries. Use those instead of running shell commands through python.

**Comment by cakekoa** [comment]
PBAs are being removed in #2442
