### ISSUE TITLE
Run AppImage in nightly tests

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1119]
Alter the Jenkins to build the AppImage and run the nightly blackbox tests against the AppImage instead of source code.

- [x] Alter Jenkins ete build to build AppImage. (0d) - @VakarisZ 
- [x] Alter Jenkins script to move AppImage to S3. (0d) - @VakarisZ 
- [x] Alter Jenkins script to ssh into Island on the zoo and download the AppImage instead of monkey binaries. (0.25d) - @VakarisZ 
- [x] Alter Jenkins script to install and run AppImage in the Island on the Zoo. (0d) - @VakarisZ 
- [x] Alter EtE scripts to set island to standard (no password protection) mode. (0d) - @VakarisZ

**Comment by VakarisZ** [comment]
Solved
