### ISSUE TITLE
Monkey Island Web UI Automated Testing

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1127]
# Spike

## Objective
Identify a testing tool or framework that will allow us to test our web UI.

### Description
In order to reduce overall defects and enable faster refactoring, we need a way to run automated tests against the Monkey Island web UI. Some tools that would enable this are:

[Jest](https://jestjs.io/)
[Cypress](https://www.cypress.io/)
[Selenium](https://www.selenium.dev/)
[React Testing Library](https://testing-library.com/docs/react-testing-library/intro/)

Perform a simple trade study that compares 3 or more of these options (and any other options you can find.)

## Scope
Timeboxed to 2 days

## Output
A simple trade study comparing at least 3 tools/frameworks that will allow us to create automated tests for the web UI.

**Comment by VakarisZ** [comment]
For v1, it would be enough to just check if we get critical errors in javascript console on any of our pages

**Comment by cakekoa** [comment]
Related: #3685

**Comment by mssalvatore** [comment]
Resolved by #3685
