### ISSUE TITLE
Performance profile for blackbox tests

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1132]
# Spike

## Objective
The entire suite of blackbox tests currently takes approximately 55 minutes to run. As we add more features, we'll be adding more tests. This runtime will only get longer.

Determine why the tests take so long to run and create new github issues that explain why the tests are slow and what we can do to speed them up.

## Scope
Time boxed: 1 day - @VakarisZ

## Output
A set of github issues that provide enough context and instruction to enable someone to speed up the blackbox tests.

**Comment by mssalvatore** [comment]
Commit 61c3efdf83e8edf9df2d9a9e23936944e8a12d71 reduced the runtime of most tests by 1 minute each.

**Comment by VakarisZ** [comment]
Finished the spike resulting in: #1372, #1371, #1369 and #1368.
