### ISSUE TITLE
Add documentation to setup section for AppImage package

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1162]
### Add a new page 🆕

**What documentation you'd like us to add?**
[ ] Add a page to the setup section that provides instructions on using the AppImage package (0.25d)

**Where in the documentation tree?**
Setup

### Edit existing content 📝

**Which page(s) do you want us to edit?**
Remove the setup page for the Debian package.

**Comment by VakarisZ** [comment]
Add documentation for OS support as well. 
So far tested:
Ubuntu 16.04 (Doesn't work)
Ubuntu 18.04 (Works)
