### ISSUE TITLE
Monkey breaks on German system language

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1175]
## Describe the bug
If the system language is German, running the monkey gives this error:
```
2021-05-17 08:28:57,836 [6184:6172:INFO] monkey.start.168: Trying to get OS fingerprint from VictimHost('192.168.99.21') with module PingScanner
2021-05-17 08:28:57,919 [6184:6172:ERROR] main.main.137: Exception thrown from monkey's start function. More info: not enough arguments for format string
Traceback (most recent call last):
  File "infection_monkey\monkey.py", line 170, in start
    finger.get_host_fingerprint(machine)
  File "infection_monkey\network\ping_scanner.py", line 56, in get_host_fingerprint
    output = " ".join(sub_proc.communicate())
  File "subprocess.py", line 964, in communicate
  File "subprocess.py", line 1317, in _communicate
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infection_monkey\main.py", line 128, in main
    monkey.start()
  File "infection_monkey\monkey.py", line 172, in start
    LOG.error("Failed to run fingerprinter %s, exception %s" % finger.__class__.__name__,
TypeError: not enough arguments for format string
2021-05-17 08:28:58,079 [6184:6172:INFO] monkey.cleanup.275: Monkey cleanup started
```

## To Reproduce
1. Configure your environment to get similar response from ping command:
```
C:\Users\localadm>ping -n 1 -w 1000 192.168.99.21
 
Ping wird ausgeführt für 192.168.99.21 mit 32 Bytes Daten:
Antwort von 192.168.99.21: Bytes=32 Zeit<1ms TTL=128
 
Ping-Statistik für 192.168.99.21:
    Pakete: Gesendet = 1, Empfangen = 1, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 0ms, Maximum = 0ms, Mittelwert = 0ms
```
2. Run the monkey
3. See error

## Expected behavior
We should document that we only support English system language and maybe consider supporting other languages in the future.

## Machine version (please complete the following information):
 - OS: Windows

## Tasks
- [x] Investigate if issue manifests only when dropper is used. (0d) @mssalvatore 
- [ ] Fix the issue. (0.25d) @mssalvatore

**Comment by TRGamer-tech** [comment]
Just to be curious, how has it been going with this issue? :)

**Comment by VakarisZ** [comment]
@TRGamer-tech thanks for checking in. We can't prioritize the different system language support right now, so we'll probably only add an entry in the documentation hub, stating, that monkey only supports English system language. If you wanna help and fix bugs occurring on foreign system languages ping me on slack, I'll help you get set up.

**Comment by TRGamer-tech** [comment]
One solution I found for this problem was to add the correct encoding to the code, so the file `ping-scanner.py` looks like this:

![image](https://user-images.githubusercontent.com/54816030/128346828-cdcf0e2d-2f24-45b5-9493-7e0e34f659dc.png)

```
Encoding = 'cp850'
sub_proc = subprocess.Popen(
	["ping", PING_COUNT_FLAG, "1", PING_TIMEOUT_FLAG, str(timeout), host.ip_addr],
	stdout=subprocess.PIPE,
	stderr=subprocess.PIPE,
	text=True,
	encoding=Encoding
)
```
