### ISSUE TITLE
Add config export to "reset environment" page

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1203]
**Is your feature request related to a problem? Please describe.**
We should add the configuration export button to the reset environment page because that's the point where a user would like to save the state of the configuration.

**Describe the solution you'd like**
Config export button present in reset environment page as well.

## Tasks
- [ ] Create a UI mockup (0.25d)
- [ ] Import the config export button component (0.5d)

**Comment by mssalvatore** [comment]
This is related to https://github.com/guardicore/monkey/issues/957

**Comment by shreyamalviya** [comment]
This page was removed in #1909. The new reset modal added in it already mentions that the configuration should be exported before completely resetting.
