### ISSUE TITLE
Travis not running

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1220]
## Describe the bug
Travis script is not running on PR's.

## Expected behavior
We should either figure out why travis is not running and maybe migrate to GH actions

## Tasks:
- [x] Figure out precisely why travis is not running (0d) @mssalvatore

**Comment by mssalvatore** [comment]
![image](https://user-images.githubusercontent.com/19957806/121942245-44af8a80-cd1e-11eb-870c-15a7641ab097.png)
