### ISSUE TITLE
Flawless Parrot installation

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#1225]
# Spike

- [x] Run Test (0d) @ilija-lazoroski 

## Objective
Test the installation of Infection Monkey on Parrot.

## Scope
The below tests are not intended to be exhaustive. Rather, they are smoke tests to verify the basic functionality of Infection Monkey on Parrot.

- [x] Infection monkey installs without errors or warnings.
- [x] Monkey Island starts without errors or warning.
- [x] No additional system changes (dependencies, settings, etc) are required to successfully install and run Monkey Island
- [x] Monkey agent can be started locally
- [x] Monkey agent successfully propagates to a victim machine
- [x] Monkey Island receives telemetry and other expected data from monkey agents

## Output

The output of this spike is a set of GitHub issues (bugs). When these bugs are resolved, we should be able to claim to have a flawless installation experience on Parrot.

**Comment by ilija-lazoroski** [comment]
![image](https://user-images.githubusercontent.com/15820737/126167248-257dc2ed-292d-4818-bacd-2e0eac5b8243.png)

![image](https://user-images.githubusercontent.com/15820737/126167396-bb225a0a-c8e2-4340-810f-48ebc27523b3.png)

![image](https://user-images.githubusercontent.com/15820737/126167466-8e5e57bb-d006-4296-82da-9c1ca713f4c7.png)

![image](https://user-images.githubusercontent.com/15820737/126167533-f232e902-2642-4c2a-82d7-97e337549766.png)
