### ISSUE TITLE
Flawless BlackArch installation

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#1226]
# Spike

- [x] Run Test (0d) - @VakarisZ 

## Objective
Test the installation of Infection Monkey on BlackArch. 

## Scope
The below tests are not intended to be exhaustive. Rather, they are smoke tests to verify the basic functionality of Infection Monkey on BlackArch.

- [ ] Infection monkey installs without errors or warnings.
- [ ] Monkey Island starts without errors or warning.
- [ ] No additional system changes (dependencies, settings, etc) are required to successfully install and run Monkey Island
- [ ] Monkey agent can be started locally
- [ ] Monkey agent successfully propagates to a victim machine
- [ ] Monkey Island receives telemetry and other expected data from monkey agents

## Output

The output of this spike is a set of GitHub issues (bugs). When these bugs are resolved, we should be able to claim to have a flawless installation experience on BlackArch.

**Comment by VakarisZ** [comment]
Resulted in https://github.com/guardicore/monkey/issues/1337
