### ISSUE TITLE
Flawless SUSE Linux installation

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#1228]
# Spike

- [x] Run Test (0d) @ilija-lazoroski 

## Objective
Test the installation of Infection Monkey on SUSE Linux. 

## Scope
The below tests are not intended to be exhaustive. Rather, they are smoke tests to verify the basic functionality of Infection Monkey on SUSE Linux.

- [x] Infection monkey installs without errors or warnings.
- [x] Monkey Island starts without errors or warning.
- [x] No additional system changes (dependencies, settings, etc) are required to successfully install and run Monkey Island
- [x] Monkey agent can be started locally
- [x] Monkey agent successfully propagates to a victim machine
- [x] Monkey Island receives telemetry and other expected data from monkey agents

## Output

The output of this spike is a set of GitHub issues (bugs). When these bugs are resolved, we should be able to claim to have a flawless installation experience on SUSE Linux.

**Comment by ilija-lazoroski** [comment]
![image](https://user-images.githubusercontent.com/15820737/126175644-9fbb2955-ba0e-41b2-9381-b5f0b171fbd2.png)

![image](https://user-images.githubusercontent.com/15820737/126175735-65b06d81-ee03-4e77-88c6-d9875efed2c4.png)

![image](https://user-images.githubusercontent.com/15820737/126175788-6b48b2da-1e03-4e17-ab26-197255723334.png)

![image](https://user-images.githubusercontent.com/15820737/126175904-418141a1-d8a8-4e94-b27e-adf2424057ae.png)
