### ISSUE TITLE
Flawless Centos 7 Installation

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1235]
# Spike

## Objective
Test the installation of Infection Monkey on Centos 7. @ilija-lazoroski 

## Scope
The below tests are not intended to be exhaustive. Rather, they are smoke tests to verify the basic functionality of Infection Monkey on Centos 7.

- [ ] Infection monkey installs without errors or warnings.
- [ ] Monkey Island starts without errors or warning.
- [ ] No additional system changes (dependencies, settings, etc) are required to successfully install and run Monkey Island
- [ ] Monkey agent can be started locally
- [ ] Monkey agent successfully propagates to a victim machine
- [ ] Monkey Island receives telemetry and other expected data from monkey agents

## Output

The output of this spike is a set of GitHub issues (bugs). When these bugs are resolved, we should be able to claim to have a flawless installation experience on Centos 7.

**Comment by ilija-lazoroski** [comment]
Created #1354 and #1355 .

**Comment by ilija-lazoroski** [comment]
Related to #1355 
Missing:
`openssl11-libs` installed with yum
`glibc-2.18`  installed with 
```# If gcc is not installed
# yum install gcc
wget http://ftp.gnu.org/gnu/glibc/glibc-2.18.tar.gz
tar zxf glibc-2.18.tar.gz 
cd glibc-2.18/
mkdir build
cd build/
../configure --prefix=/usr
make -j4
make install```
