### ISSUE TITLE
Flawless Kali 2021.2 Installation

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1236]
# Spike

## Objective
Test the installation of Infection Monkey on Kali 2021.2.

## Scope
The below tests are not intended to be exhaustive. Rather, they are smoke tests to verify the basic functionality of Infection Monkey on Kali 2021.2.

- [x] Infection monkey installs without errors or warnings.
- [x] Monkey Island starts without errors or warning.
- [x] No additional system changes (dependencies, settings, etc) are required to successfully install and run Monkey Island
- [x] Monkey agent can be started locally
- [x] Monkey agent successfully propagates to a victim machine
- [x] Monkey Island receives telemetry and other expected data from monkey agents

## Output

The output of this spike is a set of GitHub issues (bugs). When these bugs are resolved, we should be able to claim to have a flawless installation experience on Kali 2021.2.

**Comment by VakarisZ** [comment]
Probably unrelated, but resulted in #1341
![image](https://user-images.githubusercontent.com/36815064/126446356-92fb9bd6-9df1-4331-a1ff-3ac5960358dd.png)

Kali tested:
```
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2021.2
Codename:       kali-rolling
```
