### ISSUE TITLE
File permissions inspection

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1243]
# Description

As a blue team member, I want a list of all files ransomware _could_ encrypt, so that I can improve my file permissions policies.

# Acceptance Criteria

- All files on the system are inspected, including network shares and removable media.
- On Linux, omit /dev, /proc, and /sys from the scan.
- No files are modified in any way during this operation
- The ransomware simulation can be configured so that the file inspection feature is disabled.
- Ransomware configuration screen includes a checkbox that allows the user to enable/disable file inspection.
- Results of file permissions inspection are visible in the ransomware report.
- All files that were inspected and found to be writable by the monkey agent are added to a list and reported back to Monkey Island.
  - T1083 - File and Directory Discovery
  - T1005 - Data from Local System
  - T1025 - Data from Removable Media
  - T1039 - Data from Network Shared Drive
- Unit tests are written and provide comprehensive coverage.
- Documentation is written that describes how the file inspection functionality behaves.

**Comment by cakekoa** [comment]
Moved to guardicode/ransomware-payload#1
