### ISSUE TITLE
Ransomware wallpaper

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1247]
# Description

As a red team member, I want a ransomware simulation that changes the desktop wallpaper, in order to more accurately simulate ransomware attacks in my network.

# Acceptance Criteria
- Ransomware simulation changes the wallpaper on Windows systems.
- New wallpaper clearly states that this is a ransomware simulation, not real ransomware.
- The ransomware simulation can be configured so that changing wallpaper is disabled.
- Ransomware configuration screen includes a checkbox that allows the user to enable/disable changing the wallpaper.
- Unit tests are written and provide comprehensive coverage.
- Documentation is written that describes how the wallpaper functionality behaves.

**Comment by Brazilian2019** [comment]
Please assign me to this issue.

**Comment by mssalvatore** [comment]
Completed in #3861
