### ISSUE TITLE
T1486 Attack Technique (Data Encrypted for Impact)

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1249]
# Description

As a blue team member, I want to understand the actions that the Infection Monkey ransomware simulation performed within the context of the MITRE ATT&CK Framework, so that I can determine how to defend my network from ransomware attacks.

# Acceptance Criteria

- Monkey agent reports all relevant T1486 (data encrypted for impact) events to Monkey Island.
- The ATT&CK configuration UI makes a distinction between configurable and non-configurable techniques
- Unit tests are written and provide comprehensive coverage.
- New techniques are added to documentation.

**Comment by VakarisZ** [comment]
ATT&CK report is getting removed in https://github.com/guardicore/monkey/issues/2440
