### ISSUE TITLE
Unclosed file handle by get_file_descriptor_for_new_secure_file

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1252]
## Describe the bug
`monkey/monkey_island/cc/server_utils/encryptor.py:30` leaves a file handle open. Either `get_file_descriptor_for_new_secure_file` should not return a handle and the method should be renamed or the handle should be used in the proceeding statement. 

## Machine version (please complete the following information):
 - OS: Windows and Linux

**Comment by mssalvatore** [comment]
According to http://timgolden.me.uk/pywin32-docs/PyHANDLE.html, the handle should be closed when the object is destroyed (goes out of scope?).

**Comment by VakarisZ** [comment]
Maybe that's why the FD was invalid...
