### ISSUE TITLE
Refactor configuration from flat to component based

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1260]
**Is your feature request related to a problem? Please describe.**
Right now `WormConfiguration` objects has a ton of object attributes. Instead, `WormConfiguration` should have a list of configurations, relevant to specific features, a.k.a. the configuration for monkey shouldn't be flattened.

**Describe the solution you'd like**
Island shouldn't flatten the config, rather the top level dicts should end up in monkey config.

**Comment by mssalvatore** [comment]
`WormConfiguration` has been replaced by `AgentConfiguration`. The `AgentConfiguration` does not get flattened.
