### ISSUE TITLE
./config.ps1 isn't being downloaded

### ISSUE THREAD

**Issue by TRGamer-tech** [guardicore/monkey#1277]
## Describe the bug

The $webclient.downloadfile command doesn't work in combination with the deploy_windows.ps1 script.

## To Reproduce

1. Get deploy_windows.ps1 script from GitHub
2. Run it
3. See Error: 
```
The term './config.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

## Expected behavior
A description of what you expected to happen.

The script is supposed to download the config.ps1 file and execute it without any problems.

## Screenshots

![image](https://user-images.githubusercontent.com/54816030/123756615-659ae280-d8bd-11eb-9593-9186a39f9dc6.png)

## Machine version (please complete the following information):
 - OS: Windows 10

**Comment by shreyamalviya** [comment]
Hi @TRGamer-tech! `config.ps1` is downloaded to the Monkey home directory (`C:\Users\IslandAdm\Desktop\monkey` for you), but the deployment script checks for it in the current directory. Can you try running `deploy.ps1` from the Monkey home directory?

**Comment by TRGamer-tech** [comment]
I did just that and many more things together with @VakarisZ.
Nothing seems to work (at least for me)

**Comment by TRGamer-tech** [comment]
![image](https://user-images.githubusercontent.com/54816030/123913579-aa3a8280-d97e-11eb-8a54-07850945eee4.png)
Thats what it looks like (in englisch)

**Comment by shreyamalviya** [comment]
The command it should be running is `git clone --single-branch --recurse-submodules -b $branch $MONKEY_GIT_URL $monkey_home 2>&1` but since it couldn't find `config.ps1`, `$MONKEY_GIT_URL` is empty. What error do you get when you run `deploy_windows.ps1` from within `C:\Users\IslandAdm\Desktop\monkey`?

**Comment by TRGamer-tech** [comment]
I tried that as well, no results at all. When I replace the $WebClient.DownloadFile with Invoke-WebRequest it works just fine.

**Comment by mssalvatore** [comment]
@ordabach Did you see this issue when running the deployment script?

**Comment by mssalvatore** [comment]
This was resolved somewhere along the way. There are still some other issues with the deployment script, but this isn't one of them.
