### ISSUE TITLE
Windows defender flags the monkey as a malware 

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1289]
## Describe the bug
Monkey binaries are getting flagged on windows, which causes issues during the installation and run phases of the monkey.

## To Reproduce
1. Build monkey agent
2. Run monkey agent on updated windows-10 machine
3. See error

![image](https://user-images.githubusercontent.com/36815064/124090623-adf10680-da5d-11eb-8f6f-9a8681eca354.png)

## Expected behavior
The binary shouldn't get flagged

## Machine version (please complete the following information):
 - OS: Windows 10

**Comment by VakarisZ** [comment]
Possible solutions:

Signing the monkey binaries:

> The way both Microsoft and the other security vendors can tell your app from others is well known, it's by including a digital signature with your app that's produced from a code-signing certificate you've acquired from a reputable Certificate Authority which is part of the Microsoft Authenticode group of accepted certificate vendors.

**Comment by VakarisZ** [comment]
A list of potential tools to use:
 - [Invoke-Obfuscation](https://github.com/danielbohannon/Invoke-Obfuscation)
 - [AVET](https://github.com/govolution/avet)
 - [BeaEngine](https://github.com/BeaEngine/beaengine)
 - [ShellterProject](https://www.shellterproject.com/license/)

**Comment by mssalvatore** [comment]
I think that impacket is the thing that defender most often flags. We can use other projects, like [smbprotocol](https://pypi.org/project/smbprotocol/) in order to avoid tripping defender.

**Comment by mssalvatore** [comment]
https://vanmieghem.io/blueprint-for-evading-edr-in-2022/

**Comment by mssalvatore** [comment]
Fixed in v2.2.0.

Note that some behaviors/plugins may still trigger Windows Defender, but this means it's doing its job. Installation is not impeded, which was the major issue.
