### ISSUE TITLE
BlackArch AppImage bug

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1337]
## Describe the bug
Can't run AppImage in black arch

## To Reproduce
1. Download the full ISO from https://www.blackarch.org/downloads.html
2. Boot the blackarch
3. Launch the appImage
4. See error:
![image](https://user-images.githubusercontent.com/36815064/126311165-eaeee498-198d-4067-a0dc-eba459b25cf4.png)

## Expected behavior
Shouldn't throw an error

## Machine version (please complete the following information):
 - OS: BlackArch 2020.12.01

**Comment by mssalvatore** [comment]
I've been unable to reproduce this error with the blackarch OVA or slim ISO. With the full ISO, there's not enough space available to download the AppImage, which could have something to do with the original error.
