### ISSUE TITLE
Going from the landing page to the getting started page takes too much time

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#1338]
## Describe the bug
The time between someone clicking on "Ransomware" on the landing page, and the "Getting Started" page opening, is almost 10 seconds on my machine.

## To Reproduce
1. Run Monkey Island.
2. Start over if you need to.
3. On the landing page, click on "Ransomware".
4. See how long it takes to open the "Getting Started" page.

## Expected behavior
The "Getting Started" page should be shown immediately.

## Screenshots
https://user-images.githubusercontent.com/44770317/126314374-3022615d-71f5-492b-b7fc-3f7682d642e3.mp4

**Comment by ilija-lazoroski** [comment]
Checked this and the time on my machine is instantly:

![Instantly](https://user-images.githubusercontent.com/15820737/126316415-1c14656e-5a36-4fce-a5da-1ca9029009e4.gif)
