### ISSUE TITLE
Remove __author__ headers from Python files

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1345]
# Description

The "\_\_author\_\_" lines in numerous Python files serve little purpose. At best, they are redundant. At worst, they are incorrect and misleading.

The VCS (i.e. git) tracks all changes to files. Storing the author in the files is redundant violates the DRY principle.

If the file changes, whose name belongs in the \_\_author\_\_ field? What if it changes so drastically that it's almost unrecognizable? If there's any circumstance where the \_\_author\_\_ name should change, what enforces that this change takes place? Given the ambiguity of these scenarios, the \_\_author\_\_ field could be misleading or incorrect.

# Tasks
- [ ] Run blackbox tests against the [this branch](https://github.com/guardicore/monkey/tree/remove-author-header) and make sure nothing broke (0.25d) @ilija-lazoroski

**Comment by ilija-lazoroski** [comment]
![image](https://user-images.githubusercontent.com/15820737/127349078-88077cf1-1e37-46fc-8d8e-f5bbf1636d17.png)
