### ISSUE TITLE
MongoDB is not starting on CentOS 7

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#1355]
## Describe the bug
While running the AppImage on CentOS 7, the Island log showed that MongoDB has started successfully and then stuck on waitng for MongoDB server. The mongodb log shows that `libcrypto.so.1.1` is missing.

## To Reproduce
1. Run AppImage
2. Check the Island log
3. See error in `.monkey_island/mongodb.log` 

## Expected behavior
The MongoDB should have started without errors.

## Screenshots
![image](https://user-images.githubusercontent.com/15820737/126688791-cc3eba91-1a15-4c85-914b-9217603bd614.png)

![image](https://user-images.githubusercontent.com/15820737/126688857-bbc92617-c1e1-4d08-8080-2596b44125f1.png)

## Machine version (please complete the following information):
 - OS:  Linux

**Comment by ilija-lazoroski** [comment]
Missing:
`openssl11-libs` installed with yum
`glibc-2.18`  installed with 
```# If gcc is not installed
# yum install gcc
wget http://ftp.gnu.org/gnu/glibc/glibc-2.18.tar.gz
tar zxf glibc-2.18.tar.gz 
cd glibc-2.18/
mkdir build
cd build/
../configure --prefix=/usr
make -j4
make install```

**Comment by mssalvatore** [comment]
We should include the missing libraries in the AppImage so that the user does not have to take extra steps.
