### ISSUE TITLE
Add libcurl to Appimage

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1362]
Some Ubuntu systems may not have libcurl installed by default. Add it to the AppImage so that the AppImage package does not require the user to perform any extra steps to install it.

**Comment by ilija-lazoroski** [comment]
#1355 also the packages mention here.

**Comment by ilija-lazoroski** [comment]
OS: CentOS 7
MongoDB is not finding `libcurl.so.4`

![image](https://user-images.githubusercontent.com/15820737/127016337-a2bb43f4-afc3-4325-8a41-131e4c7e4c50.png)
