### ISSUE TITLE
Monkey agent is not propagating to victim machine CentOS 7

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#1366]
## Describe the bug
Monkey is not propagating on victim machine on CentOS 7 - @VakarisZ 

## To Reproduce
1. Set a victim machine
2.Run Monkey Island
3. Confirm that monkey agent is not successfully propagating to the machine.

## Expected behavior
The vulnerable machine should be able to communicate to the Monkey Island

## Screenshots

![image](https://user-images.githubusercontent.com/15820737/127018609-7465370f-985b-4c92-9b8a-542be6a9f703.png)

## Machine version (please complete the following information):
 - OS: CentOS 7

Victim Log File: 
[victim_log.txt](https://github.com/guardicore/monkey/files/6879561/user-1563.txt)

Island Log File:
[Island_log.txt](https://github.com/guardicore/monkey/files/6879583/Island_log.txt)

**Comment by mssalvatore** [comment]
This looks like it could be a firewall/networking issue, and not necessarily a monkey bug.

**Comment by mssalvatore** [comment]
Since CentOS 7 is from 2009, we're not going to support it with the AppImage package. CentOS 7 users can use the docker package instead.
