### ISSUE TITLE
Make ATT&CK telemetry's format of IP addresses uniform

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#1394]
As per [this comment](https://github.com/guardicore/monkey/pull/1393#discussion_r680927423), for the ATT&CK techniques that use the [`renderMachineFromSystemData`](https://github.com/guardicore/monkey/blob/develop/monkey/monkey_island/cc/ui/src/components/attack/techniques/Helpers.js#L11) helper function, the IP addresses collected in the ATT&CK telemetry and sent to the Island are of different types and in different formats.
As of now, there are three ways:
![image](https://user-images.githubusercontent.com/44770317/127866066-cd1cc640-5c41-4c0d-9f28-6dc5dc249020.png)
![image](https://user-images.githubusercontent.com/44770317/127866133-9655b668-7c9c-4f4a-8038-34d5128870ae.png)
![image](https://user-images.githubusercontent.com/44770317/127866190-6862d1c7-18fa-4b88-8218-5552b5f835ab.png)

This is prone to cause bugs.

We should send the IP addresses for each ATT&CK technique (that uses the aforementioned helper function) in the same format to avoid bugs when the report is generated on the Island, i.e. make sure that everything that produces the IP address field for the ATT&CK telemetry produces the same type of data in the same format.

**Comment by VakarisZ** [comment]
ATT&CK report is getting removed in https://github.com/guardicore/monkey/issues/2440
