### ISSUE TITLE
[Feature request] add an http support for reverse-proxying

### ISSUE THREAD

**Issue by andrusstrockiy** [guardicore/monkey#140]
## Actual Behaviour
Currently a web app only supports https://0.0.0.0:5000 requests with certificates handling by app itself. 
With large scale it's become more conveyanced to use a reverse-proxy (nginx,traefik) to handle https requests with proxy passing request to your back-end through http protocol.
So it would be great to have configuration file or environment variable which could change listening socket from https to http.

## Specifications

  - Version: 1.5 (not sure)
  - Platform: Docker
  - Subsystem: Debian

**Comment by andrusstrockiy** [comment]
Anyone ?

**Comment by danielguardicore** [comment]
Hello @andrusstrockiy 
The Monkey is an open source project, you're welcome to implement the change yourself and submit a pull request. 

We intend to work on this problem and others relating to certification and reverse proxy support, along with other connectivity improvements we want to do for better support for cloud networks, but this won't happen in the very near future.
