### ISSUE TITLE
Investigate how to export/import mongodb

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1461]
# Spike
Investigate how to dump/import mongodb with our current infrastructure and write up what we would have to do to make it work in monkey

## Scope
Mongodb and Monkey island

## Output
Prototypes/comments on #629 

## Tasks
- [x] Investigate and prototype the dumping and importing of mongodb mitigations collection (cross-platforming, prefer using pymongo) (0d) @ilija-lazoroski

**Comment by ilija-lazoroski** [comment]
Check #629 for output.
