### ISSUE TITLE
Investigate re-implementation of T1129

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1464]
## Describe the bug
The "Execution through module load" ATT&CK technique does not work. I believe this is because code that exercised this technique was removed in 90b47a4bb644665ebabc2d4f375f6927d440ace9. In the current code, I don't see any code that sends telemetry for T1129

## To Reproduce
1. Configure the Monkey however you like.
2. Run the monkey agent on a Windows machine.
3. Check the Mitre ATT&CK report and observe that "Execution through module load" reports that "Monkey didn't ... run on any Windows machines."

## Expected behavior
Monkey should actually simulate the module load attack technique or not be in report at all

## Screenshots
![image](https://user-images.githubusercontent.com/19957806/133304092-9362cd47-25c9-4042-b64c-e405f658ec2c.png)

## Machine version (please complete the following information):
 - OS: Windows

## Tasks:
 - [ ] Investigate if we can re-implement the T1129. If we can, open an issue with detailed steps, if not - remove from reports (timeboxed 1d) - @VakarisZ

**Comment by shreyamalviya** [comment]
Somewhat related: https://github.com/guardicore/monkey/issues/919

**Comment by VakarisZ** [comment]
[Building a dll is trivial](https://www.wikihow.com/Create-DLL-Files), though we should build a DLL that imitates malicious code. 
Loading a dll [can be done from python.](https://stackoverflow.com/questions/5253854/python-import-dll)

**Comment by VakarisZ** [comment]
Fixed by [removing the code](https://github.com/guardicore/monkey/commit/b69916428b73bb653f17db6d737db7ef109a300d) and creating [an issue #1474
