### ISSUE TITLE
Test all Mitre ATT&CK techniques

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1465]
# Spike

## Objective
Determine whether any Mitre ATT&CK techniques are broken and create an issue/bug to fix any broken techniques.

## Scope/Tasks
- [x] Test each attack technique. (0d) @ilija-lazoroski 

## Output
A set of GitHub issues/bugs that describe any broken techniques.

### Known issues
https://github.com/guardicore/monkey/issues/1464
https://github.com/guardicore/monkey/issues/919

A number of "mandatory" attack techniques are not being run. Compare two screenshots below for more information.

#### All attack techniques: 
![image](https://user-images.githubusercontent.com/19957806/133305828-73cba7c5-106c-4d4c-ae76-4e7b6943a0aa.png)

#### Report:
![image](https://user-images.githubusercontent.com/19957806/133305905-99498aa0-b827-4561-a3da-97a0a34347e5.png)

**Comment by ilija-lazoroski** [comment]
Another in the line
![image](https://user-images.githubusercontent.com/15820737/133757374-0bdfb086-6fdb-4a85-ad14-9472193d3995.png)

Not a single Windows Machine in my network. Crontab as far as I know is not Windows utility.

**Comment by shreyamalviya** [comment]
@ilija-lazoroski, I just looked into it. That seems like a bug in how the PBA telemetry is filtered for attack techniques, which occurs since the "Job scheduling" PBA is mapped to T1053 (Scheduled task) and T1168 (Local job scheduling). Nice catch. I'll open an issue with a detailed explanation.
