### ISSUE TITLE
Scripting Mitre Attack Technique is deprecated

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#1496]
**Is your feature request related to a problem? Please describe.**
Scripting Mitre Technique is deprecated. 
https://attack.mitre.org/techniques/T1064/

**Describe the solution you'd like**
Rename as advised.

**Describe alternatives you've considered**
Maybe completely remove it as we already have the technique that is advised to be used.

**Comment by VakarisZ** [comment]
ATT&CK report is getting removed in https://github.com/guardicore/monkey/issues/2440
