### ISSUE TITLE
Incorrect assumptions in account discovery

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1509]
# Description
The Linux account discovery, Linux clear command history, and Linux modify shell startup files PBAs make incorrect assumptions about Linux users.

1. Assumes all users' home directories are in `/home`
2. Assumes users' home directories have the user's name. (e.g. testuser's home directory is `/home/testuser`)
3. Assumes regular users have 4 digit IDs.

In addition, these 3 PBAs duplicate the same command.

# Proposed solution
Instead of running complicated shell commands which require `shell=True` (which is a security concern, see also https://github.com/guardicore/monkey/issues/1118), the logic for these PBAs can be reimplemented in Python.

## Correcting false assumptions
1. Rather than filtering users by the length of their ID, the code can parse the contents of `/etc/passwd` using the [Python pwd module](https://docs.python.org/3.7/library/pwd.html) and return only non-root users with the following shells:
    - bash
    - sh
    - dash
    - fish
    - zsh
    - ksh
    - csh
    - tsch
2. Get each user's home directory using the pwd module instead of assuming it's `/home/[USERNAME]`
3. Make this code reusable (and testable)

**Comment by cakekoa** [comment]
PBAs are being removed in #2442
