### ISSUE TITLE
the command "dkpg -i *.deb" in Dockerfile is wrong

### ISSUE THREAD

**Issue by nanmuyao** [guardicore/monkey#152]
## Expected Behavior
it should be run the monkey, when i build the images from the Dockerfile

## Actual Behavior
root@d1a3f433eb7b:/app# dpkg -i monkey_island.deb
(Reading database ... 12008 files and directories currently installed.)
Preparing to unpack monkey_island.deb ...
monkey-island: unrecognized service
monkey-mongo: unrecognized service
Unpacking gc-monkey-island (1.0) over (1.0) ...
Setting up gc-monkey-island (1.0) ...
/var/lib/dpkg/info/gc-monkey-island.postinst: line 11: pip2: command not found
/var/lib/dpkg/info/gc-monkey-island.postinst: line 12: virtualenv: command not found
/var/lib/dpkg/info/gc-monkey-island.postinst: line 15: /var/monkey_island/bin/python/bin/python: No such file or directory
cp: omitting directory '/var/monkey_island/ubuntu/systemd'
Failed to get D-Bus connection: Unknown error -1
Configuration file /lib/systemd/system/monkey-mongo.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Configuration file /lib/systemd/system/monkey-island.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Generating RSA private key, 1024 bit long modulus
......................................++++++
.......++++++
e is 65537 (0x10001)
Signature ok
subject=/C=GB/ST=London/L=London/O=Global Security/OU=Monkey Department/CN=monkey.com
Getting Private key
monkey-island: unrecognized service
monkey-mongo: unrecognized service
Monkey Island installation ended
root@d1a3f433eb7b:/app#

## Steps to Reproduce the Problem

  1.use docker
  2.command Expected Behavior in docker container

## Specifications

  - Version:1.5.2
  - Platform: docker debian 
  - Subsystem: mac

**Comment by danielguardicore** [comment]
@theonlydoo Can you take a look? You built this part

**Comment by nanmuyao** [comment]
and then i try it again, it has been succeed,thanks a lot.
but i see the new problem

1. run the monkey in docker,
2. i run the command in shell 
3. curl -O -k https://172.17.0.2:5000/api/monkey/download/monkey-linux-64; chmod +x monkey-linux-64; ./monkey-linux-64 m0nk3y -s 172.17.0.2:5000
 (this auto generate by https://localhost:5000/run-monkey, i change 172.17.0.2 -> localhost) 
4. and then it tips:
`curl -O -k https://localhost:5000/api/monkey/download/monkey-linux-64\; chmod +x monkey-linux-64; ./monkey-linux-64 m0nk3y -s localhost:5000

![image](https://user-images.githubusercontent.com/7760063/42734002-b26cee98-886e-11e8-832c-546c37779b7b.png)
may be something wrong? THX

**Comment by nanmuyao** [comment]
THX a lot, i try it agin, and success
