### ISSUE TITLE
Consider simplifying tunneling 

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1540]
# Spike

## Objective
Monkey agents can tunnel over an HTTP connection or a TCP connection. It is unclear what benefit there is to providing two different tunneling mechanisms. Determine whether or not one of the two tunneling mechanisms can be removed.

## Scope

- [x] Determine if both tunneling mechanisms are exercised by the blackbox tests, or if one tunneling mechanism is totally untested. (0d) @ilija-lazoroski 
- [ ] Pick either TCP or HTTP. Create a github issue for removing the other. (0.25d)

## Output
The output of this spike is one or more of:
- A new GitHub issue to capture the required work to remove one of the tunneling mechanisms
- Comments added to the code that clarify the purpose of different tunneling mechanisms
- Documentation describing the different tunneling mechanisms, their strengths and advantages, and how to enable/disable or configure them.

**Comment by ilija-lazoroski** [comment]
The tunneling mechanisms are really complex right now. The conclusion is that both of them are used in the tunneling test at the moment. Maybe there is a place that we discard HTTP and use TCP further but even that will require a fix and it is unknown how it will work in the wild. 

So there are two things that we can do.

1. Discard HTTP, use TCP and implement a fix. A short term solution as it may not work nicely for multi-hops and we will still have issues.
2. Implement our own mechanism based on some open-source projects like [proxy.py](https://github.com/abhinavsingh/proxy.py) 

For the above there is a new spike in place #1583 which its purpose is to capture the work required for each of the above.
