### ISSUE TITLE
Release testing plan v2.0

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1558]
The release testing plan template in confluence is full of redundancies, defunct features, and vague descriptions. It also lacks a coherent flow.

Rebuild the testing plan template from the ground up, ensuring that it is up to date and provides the necessary information to perform a release test (i.e. doesn't rely on tribal knowledge).

- [x] Build ATT&CK testing plan (0d) @ilija-lazoroski 
- [x] Guide for testing updating (0d) @ilija-lazoroski 
- [x] Guide for testing reporting (0d timeboxed) -@VakarisZ

## Notes
Add a step to test #1556

**Comment by ilija-lazoroski** [comment]
https://guardicore.atlassian.net/wiki/spaces/RES/pages/3613622316/Infection+Monkey+-+Testing+Plan+v2.0+DRAFT
