### ISSUE TITLE
Investigate the tunneling mechanisms

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#1583]
# Spike

## Objective
The intention of this spike is to check the difference of HTTP and TCP tunneling mechanism. As per #1540 we concluded that both of them are used in the blackbox tunneling tests and it looks that are more complex then we thought.
The initial idea is to discard HTTP as it uses requests to fulfill its purpose and use TCP, but TCP works only on one hope which is Island -> Victim A -> Victim B. 

## Scope
- [ ] Investigate TCP mechanism, why it doesn't work on multiple hop, how is used in the Island etc.
- [ ] Investigate HTTP mechanism, why it doesn't work on Victim B, work required to be removed
       ( Island -> Victim A -/> Victim B )
- [ ] Investigate a new custom proxy plugin ( example. [proxy.py](https://github.com/abhinavsingh/proxy.py) )

## Output
Issues for implementing a fix for TCP, discarding HTTP or making custom proxy plugin which each of the agents will be it's own Island.

**Comment by VakarisZ** [comment]
Wait, so HTTP and TCP don't work on multiple hops, but together they can do multiple hops?

**Comment by mssalvatore** [comment]
Fixed by #2216
