### ISSUE TITLE
Create the IMaster interface

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1593]
Create the IMaster interface in support of the agent refactor effort <sup>[1](#594), [2](https://guardicore.atlassian.net/wiki/spaces/RES/pages/2818932869/Infection+Monkey+-+Monkey+Agent+Refactor-+Phase+1+-+PDR)</sup>. Implement a mock IMaster object that utilizes the mock IPuppet object and performs a few actions.

- [x] Create the IMaster interface (0d) - @shreyamalviya 
- [ ] Create a mock Master class (0.5d) - @mssalvatore, @shreyamalviya

**Comment by shreyamalviya** [comment]
Branch: https://github.com/guardicore/monkey/compare/1593-i-master
