### ISSUE TITLE
Remove unneeded Python dependencies in agent

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1599]
Examine the requirements in `monkey/infection_monkey/Pipfile` and determine if any are unneeded and can be removed. For example, nothing depends on `pyftpdlib` and I cannot find any references to it in the code.

**Note**: `grep` and `pipenv graph` are your friends.

## Tasks
- [x] Come up with a CI or other solution to avoid unused dependencies building up. Take a look: https://pypi.org/project/pip-check-reqs/ (0d) - @shreyamalviya 
- [ ] Inspect dependencies in the Agent and remove unused packages (0.25d) - @VakarisZ

**Comment by shreyamalviya** [comment]
Regarding finding a CI solution, of the existing solutions:
- https://github.com/r1chardj0n3s/pip-check-reqs only works for requirements.txt files.
- https://github.com/terlenbach/packages_inspector only works with python 3.8 and is interactive.

From my research, no solution matching our needs currently exists.

**Comment by mssalvatore** [comment]
@shreyamalviya Can you give any more information about the `--unused` flag for pipenv? What makes it unreliable?

**Comment by shreyamalviya** [comment]
I ran `pipenv check --unused .` in `monkey_island/` and got the following:

<img src="https://user-images.githubusercontent.com/44770317/142983017-aff890c3-6b30-46a3-a3eb-243a78bbdc91.png" width=500>

A lot of these are used directly in our code.
