### ISSUE TITLE
File deletion techniques does not have explanation message if not attempted

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#1622]
## Describe the bug
File deletion not attempted message is empty in ATT&CK report.

## To Reproduce
1. Configure Monkey with default config
2. Run the monkey on specific machine
3. Check ATT&CK report and see empty message under File Deletion technique

## Expected behavior
It should show something like: 
![image](https://user-images.githubusercontent.com/15820737/142667683-16fbe32f-a734-4386-9e3e-46594c862726.png)

## Screenshots
![image](https://user-images.githubusercontent.com/15820737/142667650-4e573fed-c36e-474a-b5e1-c6ce048384bd.png)

## Machine version (please complete the following information):
 - OS: Windows or Linux

## Tasks

- [ ] Add unscanned message to T1107

**Comment by shreyamalviya** [comment]
This happens because T1107 does not have an unscanned message defined for it (not sure why), and none of the conditions to add reasons are met, so the string is left empty. We simply need to define the unscanned message in `T1107.py`.

**Comment by VakarisZ** [comment]
ATT&CK report is getting removed in https://github.com/guardicore/monkey/issues/2440
