### ISSUE TITLE
RemoteRunAwsService adds unnecessary delay to Island startup

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1636]
When Monkey Island starts, it checks to see if it's running on an AWS instance. When it performs this check, it makes 2 calls, each with a 2-second timeout. In the case where the Island is not running on an AWS instance, this adds approximately 2-4 seconds to the startup of the Island. For users, this is a mild inconvenience. For developers, it's a full-blown annoyance.

Find a way to eliminate this delay. Possible solutions might be:
1. Lazy-load the AwsInstance object in RemoteRunAwsService, so that it's not actually created until it's need.
2. Initialize the RemoteRunAwsService on a separate thread so that it does not delay the rest of the startup process.

Note: This doesn't seem to be an issue while running from source on Windows (with pycharm) but does manifest when run from the MSI. It also manifests while running from source on Linux.

## Tasks
- [ ] Fix it! (0.5d) - @VakarisZ

**Comment by acepace** [comment]
Why even have the 2 second timeout? If it's calling the AWS metadata instance, that should be a sub 250ms call.

**Comment by mssalvatore** [comment]
> Why even have the 2 second timeout? If it's calling the AWS metadata instance, that should be a sub 250ms call.

Is there any documentation from AWS regarding this? I'm not sure what an appropriate timeout would be, what guarantees AWS makes about its network latency, and what other variables are in the mix. My guess is it's set that high to prevent a false negative as a result of a temporary network disruption.
