### ISSUE TITLE
Speed up BB EtE tests

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1674]
**Is your feature request related to a problem? Please describe.**
blackbox tests take a long time to run

**Describe the solution you'd like**
1. Find out if it's possible to add timestamps to jenkins log messages/console output to know how log each step takes.
2. Analyze and speed up black-box tests. Some steps that take a long time, but are not necessary: building UI, downloading aws_cli and mongo containers that are already present and so on...

**Comment by mssalvatore** [comment]
#1675, #1676, and the effort to refactor the agent may resolve a lot of this pain. I'd suggest we wait until after those efforts to complete before attempting to resolve this issue.

**Comment by VakarisZ** [comment]
Solved to an extent
