### ISSUE TITLE
Undescriptive failure output in "PowerShell" ATT&CK technique

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#1678]
## Describe the bug
When PBAs "Modify files' timestamps" and "Modify shell startup files" are run, their output shows up under the "PowerShell" ATT&CK technique (T1086), since they both use PowerShell scripts. However, when they fail, the output, which is the error thrown, makes no sense.

## To Reproduce
1. Configure the Monkey with the "Modify files' timestamps" PBA enabled.
2. Run the Monkey on a Windows machine with execution policy set to `Restricted` (run `Set-ExecutionPolicy Restricted` in PowerShell; `Get-ExecutionPolicy` to check current value).
3. Make sure the PBA failed from the Security report.
4. Check the "PowerShell" technique in the ATT&CK report.

## Expected behavior
A descriptive failure message.

## Screenshots
![image](https://user-images.githubusercontent.com/44770317/150804254-557f0199-61a2-4dd7-9526-b0847beeb2fa.png)

## Machine
 - OS: Windows

**Comment by VakarisZ** [comment]
ATT&CK report is getting removed in https://github.com/guardicore/monkey/issues/2440
