### ISSUE TITLE
Reset to default button should work per configuration page

### ISSUE THREAD

**Issue by Piesa** [guardicore/monkey#1777]
I was trying to reset only ATT&CK tab in the configuration page but I've changed all the config to default. 
For me it's misleading as I'd guess that I'll reset only the current tab, not the whole config. 

**Describe the solution you'd like**
"Reset to default" button should work per configuration tab, or there should be two, "Reset config to default" and "Reset <tab_name> to default". 

**Describe alternatives you've considered**
Send a popup informing, that whole config will be wiped on confirmation.

**Comment by mssalvatore** [comment]
@Piesa You're right, this behavior is confusing. The ATT&CK configuration page has many confusing and counterintuitive behaviors. It's been removed from our development branch and will also be removed from future versions of Infection Monkey (see https://github.com/guardicore/monkey/issues/1532). It may be replaced by something better down the road.
