### ISSUE TITLE
Modify shell startup file PBA Windows

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1844]
## Describe the bug
Modify shell startup file PBA on Windows always returns success, because `C:\Users\vzilius\Desktop\infection_monkey\monkey\infection_monkey\post_breach\shell_startup_files\windows\modify_powershell_startup_file.ps1` always exit with 0 even if error occurs

## Screenshots
![image](https://user-images.githubusercontent.com/36815064/161248167-26ac3af6-5f1b-4fbb-8ce8-2243ccb8b8b1.png)

## Machine version (please complete the following information):
 - OS: Windows

**Comment by cakekoa** [comment]
PBAs are being removed in #2442
