### ISSUE TITLE
Snyk protect was removed

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#1857]
## Describe the bug
Snyk protect was removed on 31 March 2022. We need to use '@snyk/protect'.

## To Reproduce
1. Run `npm ci` in `monkey_island/cc/ui`
2. Check the warning message

## Screenshots
<img width="868" alt="image" src="https://user-images.githubusercontent.com/15820737/161716484-914858ac-089f-4f67-88a7-f0d0731659a5.png">

## Machine version (please complete the following information):
 - OS: Windows or Linux

**Comment by VakarisZ** [comment]
Fixed in #1866
