### ISSUE TITLE
Agent logs on island

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1877]
## Describe the bug
When a user runs the agent on the island, agent logs get dumped into island logs as well.

## To Reproduce
1. Press "run on island"
2. Wait for it to finish
3. Download island logs. Monkey logs are there as well.

## Expected behavior
Island logs should only contain logging messages from island.

## Tasks

- [ ] ~Fix it (0.75d)~

## Machine version (please complete the following information):
 - OS: Windows and Linux

**Comment by mssalvatore** [comment]
@VakarisZ I tested this on Windows and Linux and have been unable to reproduce this.
