### ISSUE TITLE
Choose source mapping UI styling that fits

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#1879]
# Spike
One of the reason that UI build is so slow is that we use `source-map` for production and `eval` mapping styling for development. `source-map` is the slowest on build and slowest on rebuild but it is for production and generates the best source maps. 

There is a [table of mappings styles](https://webpack.js.org/configuration/devtool/#for-development) which we can choose for our production.

## Objective
Choose which source mapping styling fits best for production.

## Output
Probably one-liner commit with new styling or explanation why what we have is the best.

**Comment by mssalvatore** [comment]
After a discussion, it seems that `soure-map` is appropriate for production and `eval` is appropriate for development.
