### ISSUE TITLE
Adding different SSH key extensions

### ISSUE THREAD

**Issue by Piesa** [guardicore/monkey#1882]
**Is your feature request related to a problem? Please describe.**
Currently as far as I understand Monkey Agent is searching resident system home directory for SSH keys to steal, looking especially for <filename>.pub and after finding one, looking for <filename> with corresponding private key. 

The problem is that monkey is ignoring the <filename>.pem or <filename>.ppk also containing private keys. 

Additionally, it should in my opinion search for them even if the pubkey won't be there, as often there are only privkeys stored in a location. 

**Describe the solution you'd like**
Monkey Agent should gather also gather other popular key extensions, like .pem, .ppk, or even check the text files that are same name as .pub file. 
Also searching for full pair should not be nesscescary.

**Describe alternatives you've considered**
Leaving it as it is, as it's working with <filename>.pub and <filename> pair. 

Cheers!

**Comment by mssalvatore** [comment]
When resolving this issue, take a peek at https://github.com/guardicore/monkey/issues/1509. The SSH collector may be making similar assumptions.
