### ISSUE TITLE
BB tests fail

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1885]
## Describe the bug
MSSQL fails when ran in depth_1_a groups, but is successful on its own
Hadoop (especially 10.2.2.3) tends to fail, perhaps increase GCP machine boot time or hadoop machine resources?

## Tasks

- [x] Fix MSSQL Test (0d) @mssalvatore 
- [ ] Fix Hadoop test (0.75d) @mssalvatore

**Comment by mssalvatore** [comment]
Here's a clue about the hadoop test:

![image](https://user-images.githubusercontent.com/19957806/163442101-e9296721-b3a2-4d09-891e-02f7b1377b09.png)

**Comment by mssalvatore** [comment]
The hadoop service is not starting when the VM boots
![image](https://user-images.githubusercontent.com/19957806/163452381-e9505f7f-e514-4267-9fff-a608fac0badb.png)

![image](https://user-images.githubusercontent.com/19957806/163452445-53680a86-0b0e-48c5-873a-0974508edb49.png)

**Comment by mssalvatore** [comment]
The issue with the hadoop test was that it was taking something like 95 seconds from the time the instance was started until the hadoop service was ready to handle requests. I solved this problem by switching the storage type from HDD to SSD. This drops the lag time from 95 seconds to 39 seconds. The test passes reliably now.
