### ISSUE TITLE
Investigate switching from Advanced Installer to something else

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1907]
# Spike

## Objective
Investigate other options for building an MSI. Determine if any of these options are viable alternatives:

- https://briefcase.readthedocs.io/en/latest/
- https://jrsoftware.org/isinfo.php
- https://nsis.sourceforge.io/Main_Page

## Scope
Time boxed to 2 days - @VakarisZ 
Time remaining: 0d
## Output
A trade study comparing different options
GitHub issues capturing any work to migrate from AdvancedInstaller to a better option (if there is a better option)

**Comment by VakarisZ** [comment]
## Time comparison:
**Advanced installer**:
```Total build time: 7 min 43 sec.```
Jenkins build time: `Took 17 min`

**Inno setup** (no signing, no compression):
``` 00.09.32 elapsed``` (9 seconds)

**Inno setup** (no signing, lzma2 compression):
``` 03.09.25 elapsed``` (3 mins, 9 seconds)
