### ISSUE TITLE
Remove unnecessary mongo binaries from build artifacts

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1913]
The Mongo installation includes a number of binaries that are not necessary for Infection Monkey to function. For example, here is the complete listing on Linux:
```
total 298M
drwxr-x--- 3 ubuntu ubuntu 4.0K Nov  7 23:48 ../
-rwxr-x--- 1 ubuntu ubuntu  13M Nov  7 23:48 bsondump*
-rwxr-x--- 1 ubuntu ubuntu  17M Nov  7 23:48 mongostat*
-rwxr-x--- 1 ubuntu ubuntu  17M Nov  7 23:48 mongoexport*
-rwxr-x--- 1 ubuntu ubuntu  18M Nov  7 23:48 mongoreplay*
-rwxr-x--- 1 ubuntu ubuntu  46M Nov  7 23:48 mongo*
-rwxr-x--- 1 ubuntu ubuntu  17M Nov  7 23:48 mongoimport*
-rwxr-x--- 1 ubuntu ubuntu  18M Nov  7 23:48 mongorestore*
-rwxr-x--- 1 ubuntu ubuntu  39M Nov  7 23:48 mongos*
-rwxr-x--- 1 ubuntu ubuntu  16M Nov  7 23:48 mongotop*
-rwxr-x--- 1 ubuntu ubuntu  17M Nov  7 23:48 mongodump*
-rwxr-x--- 1 ubuntu ubuntu  69M Nov  7 23:48 mongod*
-rwxr-x--- 1 ubuntu ubuntu  17M Nov  7 23:48 mongofiles*
-rw-r----- 1 ubuntu ubuntu  30K Nov  7 23:48 LICENSE-Community.txt
-rwxr-x--- 1 ubuntu ubuntu 7.6K Apr  1 00:16 install_compass*
drwxr-x--- 2 ubuntu ubuntu 4.0K Apr  1 00:16 ./
```

I suspect we only need `mongod` and `LICENSE-Community.txt`

For the AppImage and MSI builds, remove unnecessary binaries.

## UPDATE
It appears the AppImage artifact does not contain anything other than the license and mongod binary.

## Tasks

- [ ] Modify the MSI build to exclude all files except the license and `mongod` binary. (0.75d) @ilija-lazoroski

**Comment by ilija-lazoroski** [comment]
I have removed the unneeded binaries from the storage and tested. There is no need of updating the aip file as it gets automatically synchronized.

There is drastic size reduction: from 225Mb to 149Mb for the executable, similar as AppImage and Docker. Also the installation of the MSI: 1.3Gb to 612Mb. Great Success! 😄 

<img width="344" alt="image" src="https://user-images.githubusercontent.com/15820737/166082587-be0a3e08-01a8-4ac5-85bd-f1dbddb05745.png">

Old:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/15820737/166082605-896040b7-7fbc-4d56-a5d0-111f5f9ae300.png">

New:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/15820737/166082634-6447b4a2-98ca-44ff-a327-59b8975df0f3.png">
