### ISSUE TITLE
Implement UAC bypass

### ISSUE THREAD

**Issue by danielguardicore** [guardicore/monkey#192]
If the Monkey connects over RDP to a Windows machine with UAC activated, regardless of credentials it needs to bypass UAC in order to install itself.
## Expected Behavior
Monkey should detect it's in a UAC enabled env and bypass UAC using any common technique.
A list of techniques is available here
https://github.com/hfiref0x/UACME

## Actual Behavior
UAC popup

## Steps to Reproduce the Problem

  1. Use the RDP grinder to connect using admin credentials to UAC enabled machine.
  2. Observe

Or run the Monkey on a UAC enabled machine, using admin credentials, from a regular command prompt.

## Specifications

  - Version: All
  - Platform: Windows

**Comment by VakarisZ** [comment]
Is it still valid even though we don't support RDP any longer?

**Comment by VakarisZ** [comment]
Clossing, because we no longer support RDP
