### ISSUE TITLE
Att&ck report using old version (v6)

### ISSUE THREAD

**Issue by RobinvandenHurk** [guardicore/monkey#1922]
## Describe the bug
The Att&ck report generation is using a older version of the Mitre Att&ck framework (v6 or lower). The current version is v11

## To Reproduce
1. Run the monkey
2. View the Att&ck report
3. View technique "Trap" under tactic "Execution"

## Expected behavior
To see technique "Trap" under Privilege Escalation and Persistence, as per documented by Mitre

These are the documentation files of the Execution tactics. 
Version 6: https://attack.mitre.org/versions/v6/tactics/TA0002/
Version 11 (Latest): https://attack.mitre.org/tactics/TA0002/

Also, the documentation of Trap (As linked in InfectionMonkey), which clearly shows the tactics Privilege Escalation and Persistence:
https://attack.mitre.org/techniques/T1546/005/

## Screenshots
![image](https://user-images.githubusercontent.com/24567349/165792558-04a1b525-3ff8-4338-b178-c9a1f15fd236.png)

## Machine version (please complete the following information):
 - OS: Linux, but I don't think that matters

**Comment by VakarisZ** [comment]
ATT&CK report is getting removed in https://github.com/guardicore/monkey/issues/2440
