### ISSUE TITLE
Investigate Jenkins island timeouts

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#1925]
# Spike

## Objective
Running in Jenkins there are two timeouts that we have set. Now that the Monkey is faster we need lower those times. Linux machine boot timeout needs to be something like 45s and msi island start timeout is 10min, which now should definitely lower ( something like 6min. )

## Scope
Just run Jenkins tests without rebuilding and check timeouts. Timeboxed to 0.5d.

## Output
Lower timeouts to Jenkins tests.

**Comment by ilija-lazoroski** [comment]
Checking for MSI installation can be done using `tasklist`. We can check for every 20sec if the installer process has finished which is something similar to #1900 . This is going to throw away the MSI island start timeout.

**Comment by mssalvatore** [comment]
While fixing #1921, I lowered the island start timeout to 45 seconds. I also fixed the 10-minute timeout for the Windows island. See https://github.com/guardicore/labs/commit/406512922404767e1c7b7c0bb4e1aae553ecf5de and https://github.com/guardicore/labs/commit/558001c7d6609063bdaf1ad83d2e4ce49eb7f431.

@ilija-lazoroski Based on the above 2 commits, let me know if we can just consider this resolved.

**Comment by ilija-lazoroski** [comment]
> While fixing #1921, I lowered the island start timeout to 45 seconds. I also fixed the 10-minute timeout for the Windows island. See [guardicore/labs@4065129](https://github.com/guardicore/labs/commit/406512922404767e1c7b7c0bb4e1aae553ecf5de) and [guardicore/labs@558001c](https://github.com/guardicore/labs/commit/558001c7d6609063bdaf1ad83d2e4ce49eb7f431).
> 
> @ilija-lazoroski Based on the above 2 commits, let me know if we can just consider this resolved.

Nice job!
