### ISSUE TITLE
Test the AppImage package on Ubuntu 22.04

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1933]
Ubuntu 22.04 is the latest LTS release. Test the AppImage package and ensure it works properly with Ubuntu 22.04.

~Also, update the `monkey\monkey_island\linux\install_mongo.sh` script to download the relevant mongo version.~
Done in #1947.

- [ ] Test it (0.25d) - @VakarisZ

**Comment by DanielxBlack** [comment]
Hello,

I am running the following:

$ cat /etc/*lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

Would this be something I could assist in testing (if testing is still required).

**Comment by mssalvatore** [comment]
@DanielxBlack Sure! You can download [InfectionMonkey-v1.13.0.AppImage](https://github.com/guardicore/monkey/releases/download/v1.13.0/InfectionMonkey-v1.13.0.AppImage) and test it out and let us know if you run into any trouble. Be sure to attempt to reproduce any errors you find on 20.04 so we know whether or not the issue is specific to 22.04.

**Comment by DanielxBlack** [comment]
I apologize for the slowness of my response. I am currently installing.

**Comment by DanielxBlack** [comment]
I don't know if this is the best place to ask, or if it's something I should verify via documentation, but:
- Should configuring the attack "Scan Target List" *only* attack the intended target? (i.e. I did not set other IPs to ignore, but all were seemingly scanned. I can check output logs for more info if needed.).
- I intentionally configured a VM with a poor username/password and added to the configuration (enabled SSH/password auth). I need to re-test/re-validate, but it doesn't seem that I got a successful breach. I can keep testing the config, or check some logs to see if it attempted a brute-force.

**Comment by mssalvatore** [comment]
> I don't know if this is the best place to ask, or if it's something I should verify via documentation, but:

Here is fine, but you'll get faster answers and the ability to have a conversation by joining [our slack workspace](https://join.slack.com/t/infectionmonkey/shared_invite/enQtNDU5MjAxMjg1MjU1LWM0NjVmNWE2ZTMzYzAxOWJiYmMxMzU0NWU3NmUxYjcyNjk0YWY2MDkwODk4NGMyNDU4NzA4MDljOWNmZWViNDU)

>     * Should configuring the attack "Scan Target List" _only_ attack the intended target? (i.e. I did not set other IPs to ignore, but all were seemingly scanned. I can check output logs for more info if needed.).

There's a checkbox to enable/disable scanning the local subnet. If it's checked, it'll scan all local subnets in addition to whatever is configured in the "Scan Target List".

>     * I intentionally configured a VM with a poor username/password and added to the configuration (enabled SSH/password auth). I need to re-test/re-validate, but it doesn't seem that I got a successful breach. I can keep testing the config, or check some logs to see if it attempted a brute-force.

If you re-test and see the same issue, could you send me the logs? Either attach them here or join up on slack and DM them to me.

**Comment by VakarisZ** [comment]
AFAIK all we need to do is [improve the documentation](https://github.com/guardicore/monkey/issues/2907). Other than that everything works as expected
