### ISSUE TITLE
Fix UI of MSI installer

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1989]
## Describe the bug
Small bugs in MSI installer UI, like text color.
This was probably caused by updated advanced installer version.
Also, we should wait for license and see if this only happened due to the trial version (unlikelly).

## To Reproduce
Build and run the installer

## Expected behavior
The UI should be roughly the same to what we had in 1.13

## Screenshots
![image](https://user-images.githubusercontent.com/36815064/172393334-6fdd131f-5140-41c4-95dd-98caa6be8c92.png)

## Machine version (please complete the following information):
 - OS: Windows

**Comment by mssalvatore** [comment]
Fixed by https://github.com/guardicode/monkey-build/pull/8
