### ISSUE TITLE
Issue with Exporting configuration to the file of choice

### ISSUE THREAD

**Issue by Piesa** [guardicore/monkey#2011]
## Describe the bug
When Exporting current configuration I'm not asked for place where too save the file and under what name. I believe it was working correctly in previous versions. 

## To Reproduce
I'm using and Azure build of Infection monkey with Firefox
1. Log in to web interface
2. Go to Configuration tab
3. Click on Export 

## Expected behavior
Should be prompted with window to specify file location and name

## Machine version (please complete the following information):
 I'm using and Azure build of Infection monkey on linux with Firefox

**Comment by ilija-lazoroski** [comment]
Hey @Piesa , can you confirm in which version we do have modal to chose config location and name when we export? I have tried all the versions from 1.8.0 to the latest and in all of them we have default name `monkey.conf`

**Comment by VakarisZ** [comment]
This can be solved with browser configuration, closing. 
![image](https://user-images.githubusercontent.com/36815064/175040796-0c2425d8-f5c6-4979-a85d-3598fc15aeba.png)
