### ISSUE TITLE
Merge control client and control channel

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2014]
**Is your feature request related to a problem? Please describe.**
`monkey/infection_monkey/cc/control.py:ControlClient` and `monkey/infection_monkey/cc/control_channel.py:ControlChannel` have similar responsibilities of communicating with an island. 

**Describe the solution you'd like**
Merge both of these files together or separate them into specific concerns.
Consider refactoring further to make infrastructure extendable, example: 
![image](https://user-images.githubusercontent.com/36815064/173335434-9edc6567-8780-4a4e-8fb6-a6494692aedb.png)

**Comment by mssalvatore** [comment]
The original intent was for the `ControlChannel` to be a [strangler](https://martinfowler.com/bliki/StranglerFigApplication.html) and replace `control.py`.

**Comment by mssalvatore** [comment]
After #2272, `control.py` will be gone.
