### ISSUE TITLE
Valid Linux custom PBA filename is invalid on Windows Island.

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2119]
## Description
Rules about valid Linux file names are much more permissive than Windows file names. When a custom Linux PBA file is submitted to a Windows Island, the file may not be able to be written to disk if it violates Windows file naming rules.

## Proposed solution

Convert PBA file names to base64url

### Caveats
Some filenames could potentially resolve to reserved Windows files. For example, `5B` encodes to `NUL`, which is reserved. This could be easily remedied by applying a prefix to all base64url encoded file names.

If possible, let's delay this work until we refactor Custom PBAs as a payload.

## Alternative solutions
1. Only allow Linux custom PBA files to use Windows-safe filenames
2. Store files in MongoDB instead of on disk

**Comment by cakekoa** [comment]
PBAs are being removed in #2442
