### ISSUE TITLE
Domain related recommendations should not show up if empty

### ISSUE THREAD

**Issue by danielguardicore** [guardicore/monkey#213]
**Describe the bug**
We always display `domain related recommendations` even if no such issues exist.

**To Reproduce**
1. Run monkey 
2. Generate report
3. See error

**Expected behavior**
Heading should not show up

**Comment by Dhayalanb** [comment]
@danielguardicore  @itaymmguardicore  @MaorCore  
Deployed a fix by checking if the object is empty before displaying `domain related recommendations`

`{Object.keys(this.state.report.recommendations.domain_issues).length !=0 ?
                     <h3>Domain related recommendations</h3> : null }   `

**Comment by danielguardicore** [comment]
Thanks, please open this as a PR

**Comment by ShayNehmad** [comment]
@Dhayalanb fixed this based on your PR - you can see it here https://github.com/guardicore/monkey/pull/304

Thanks a lot! 🏆

**Comment by Dhayalanb** [comment]
@ShayNehmad  Glad to be of help :)
