### ISSUE TITLE
Securely pass data to executable

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2137]
# Spike

## Objective
As discussed in #2049, an environment variable can be used to pass an OTP to an agent on Linux. This prevents other users on the system from being able see the OTP by using the `ps` command or other similar mechanism. We need to determine a safe way to pass a OTP to an Agent binary on Windows

## Output
A plan for how a OTP can be passed to an agent executable on Windows. Include any caveats and alternative options.

Time remaining: 0.25d

**Comment by VakarisZ** [comment]
In windows admin users can list other users processes (with cmd parameters) AND environmental variables. 
If the user is not admin, it can't see any processess running in the context of another user. 
So it doesn't matter if we use cmd parameters or environmental variables, both can be seen by admins and neither can be seen by other users.

**Comment by stiv-kupchik** [comment]
This is half correct - two users running in the same session can see each other's processes and command lines, even without admin privs. This is quite unlikely to happen as different users are usually run under different session, but it is possible to execute code across sessions (I remember doing something like this when I was in the army, but it was very hacky and might've required admin). Environment variables get a similar treatment I believe.
Why not use a (named) pipe on Windows? Or WriteProcessMemory (if the OTP is passed between two processes on the same machine). Or if you just pass the executable and run it, why not add it as a resource to the PE file? Or just append to end of file?

**Comment by mssalvatore** [comment]
> Or just append to end of file?

If it's appended to the file, than anyone who can read the file has the OTP.

**Comment by VakarisZ** [comment]
We decided to use the environmental variable. Windows users being able to see other users environmental variables are unlikelly and we can't protect against administrators. Closing, appending info to #2049
