### ISSUE TITLE
Investigate replacing our authentication with Flask-Security

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2170]
# Spike

## Objective
Formulate a plan to replace as much of our authentication system with Flask-Security as possible.

## Output
A set of tasks on https://github.com/guardicore/monkey/issues/2157.

Time remaining: 0d - @VakarisZ

**Comment by VakarisZ** [comment]
Regardless of the package we use we still need to handle login validation logic and hashing. Flask-security don't handle hashing, it basically just wraps `brcypt`. It does what we're doing now, except hides it behind wrappers. Those wrappers allow us to change hashing library/algorithm easier, but also couples us more to flask-security.

**Comment by VakarisZ** [comment]
Closing, #2157 got updated with the findings
