### ISSUE TITLE
sambacry_monkey_runner fails to compile

### ISSUE THREAD

**Issue by ecrsecurity** [guardicore/monkey#218]
**Describe the bug**

sambacry_monkey_runner generates the following error during compilation.

sc_monkey_runner.c: In function ‘samba_init_module’:
sc_monkey_runner.c:106:2: error: ‘strncat’ specified bound 1 equals source length [-Werror=stringop-overflow=]
  strncat(commandline, " ", 1);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
gcc: error: sc_monkey_runner.o: No such file or directory
gcc: fatal error: no input files
compilation terminated.
rm: cannot remove 'sc_monkey_runner.o': No such file or directory
strip: 'sc_monkey_runner64.so': No such file
sc_monkey_runner.c: In function ‘samba_init_module’:
sc_monkey_runner.c:106:2: error: ‘strncat’ specified bound 1 equals source length [-Werror=stringop-overflow=]
  strncat(commandline, " ", 1);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
gcc: error: sc_monkey_runner.o: No such file or directory
gcc: fatal error: no input files
compilation terminated.
rm: cannot remove 'sc_monkey_runner.o': No such file or directory
strip: 'sc_monkey_runner32.so': No such file

This appears to be a problem with string truncation.

**To Reproduce**
1. Configure the Monkey with X settings
2. Run the monkey on specific machine
3. See error

1. Install dependencies
2. cd into sambacry dir
3. run build.sh

**Expected behavior**
A description of what you expected to happen.

Compiling a  working binary

**Screenshots**

**Machine version(please complete the following information):**
 - OS: Windows or Linux

Kali Linux

**Comment by danielguardicore** [comment]
Nice! We compile using an older version of gcc and missed this analysis. Will check it out
