### ISSUE TITLE
Fix trivial UI stuff in ATT&CK report

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#2213]
## Describe the bug
1. The dropdown arrow in the "List of all techniques" section is reversed. It should point downwards (showing what will happen next).
2. When hovering over an attack technique in the "List of all techniques" section, only the ones in dark gray, i.e. the techniques not attempted, change their text color from white to black. This responsiveness should be consistent: either present for all or for none.

## To Reproduce
1. Generate the reports and notice all of these issues in the ATT&CK report

## Screenshots
![image](https://user-images.githubusercontent.com/44770317/186604760-e008b9ba-1fbf-44f0-acec-6780f7cfb481.png)

**Comment by VakarisZ** [comment]
ATT&CK report is getting removed in https://github.com/guardicore/monkey/issues/2440
