### ISSUE TITLE
Remove all code related to `ScanStatus.DISABLED` in UI

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#2214]
# Refactor

## Component(s) to be refactored
- UI

## Explanation
Code related to disabled attack techniques was removed in https://github.com/guardicore/monkey/pull/1618. Some residual of this/dead code is left in the UI. Remove it.

![image](https://user-images.githubusercontent.com/44770317/186606921-844b9b26-9713-4dbf-9f70-b1e60cf8e802.png)

**Comment by VakarisZ** [comment]
ATT&CK report is getting removed in https://github.com/guardicore/monkey/issues/2440
