### ISSUE TITLE
Implement `INodeRepository` using mongodb

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2255]
## Description

Create a `MongoNodeRepository` that implements `monkey_island.cc.repository.INodeRepository` 

![image](https://user-images.githubusercontent.com/19957806/189140156-4362f87e-3779-4383-b98e-cb7c4b26906a.png)

## Tasks
- [ ] Implement `MongoNodeRepository`  (0.25d) @mssalvatore

**Comment by VakarisZ** [comment]
Why are connections not just part of `Machine`?
