### ISSUE TITLE
Inconsistency in the way empty lists are shown in the Security report

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#2288]
## Describe the bug
Empty lists are shown inconsistently in the UI.

## To Reproduce
1. Run the Island
2. Configure it to have 0 usernames and 0 credentials for brute-forcing
3. Run the Agent (just to generate the report)
4. Check Security report

## Expected behavior
Empty lists should be shown in the UI in a consistent way.

## Screenshots
![image](https://user-images.githubusercontent.com/44770317/190177132-401b038c-a4f5-4846-a812-8d3a007c4308.png)

## Tasks
- [x] Fix list display (0d) - @shreyamalviya 
- [ ] Fix duplicate credentials (0.5d) - @VakarisZ

**Comment by VakarisZ** [comment]
In addition, credentials are duplicated: 
![image](https://user-images.githubusercontent.com/36815064/198222257-57833ce2-80b2-41d6-b919-d3036e70acd0.png)
