### ISSUE TITLE
Direct all GitHub links in documentation to `master` branch

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#2308]
### Edit existing content 📝

**Which page(s) do you want us to edit?**
Multiple

**What do you think should be changed?**
Any links in the documentation that redirect to our GitHub repo should go to the `master` branch, not the `develop` branch. Almost always, `develop` has lots of changes as compared to `master`. This is especially important for everything in the contributing section.

Related: #2132

**Comment by Akhil-Sharma30** [comment]
Can I work on this issue?
