### ISSUE TITLE
Island should offer option to download with wget and not curl

### ISSUE THREAD

**Issue by danielguardicore** [guardicore/monkey#231]
**Describe the bug**
Curl is not installed on all machines, typically either wget or curl are installed.

**To Reproduce**
Use debian, which does not come default with curl.

**Expected behavior**
Script should support both or provide two options.

**Comment by d80ep08th** [comment]
Hi , I am a beginner here. How do= I begin with this problem?

**Comment by danielguardicore** [comment]
Was fixed as part of #238
