### ISSUE TITLE
Remove FAQ no longer relevant from documentation

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#2311]
### Edit existing content 📝

**Which page(s) do you want us to edit?**
FAQ

**What do you think should be changed?**
Remove the "Exactly what internet queries does the Infection Monkey perform?" FAQ since it's no longer relevant. This feature was removed in #1420.
Check other FAQs for relevancy and consistency too.

**Comment by mssalvatore** [comment]
We still use the second query, which is to check updates.infectionmonkey.com. It needs to be updated, though.

**Comment by shreyamalviya** [comment]
Done in #2938
