### ISSUE TITLE
Needless event registration in the serializer

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2378]
# Refactor

## Component(s) to be refactored

register_common_agent_event_serializers

## Explanation

There should be a PydanticAgentEventSerializerRegistry that would serialize all events with PydanticAgentEventSerializer by default. 
If we wanted different serialization, then we would register it. So far there's no point in having to manually register each event when they all are serialized the same way.

**Comment by mssalvatore** [comment]
Migrated to https://github.com/guardicode/monkeytypes/issues/14
