### ISSUE TITLE
TCP scanner waits for 200 SECONDS between scans by default

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#246]
In monkey config default wait time between tcp scans should be 200 miliseconds:
![image](https://user-images.githubusercontent.com/36815064/51672541-62a4b500-1fd4-11e9-9d30-507f2f5e1afd.png)
Network scanner pulls this value (200) and starts waiting:
![image](https://user-images.githubusercontent.com/36815064/51672621-9ed81580-1fd4-11e9-8a8f-1b8d5a99d8c6.png)
But the wait time is actually in seconds:
![image](https://user-images.githubusercontent.com/36815064/51672458-312be980-1fd4-11e9-81d6-edf0762cbf77.png)

So the bug is either in UI(it should be seconds, not miliseconds) or in the backend(it should wait for miliseconds instead of seconds)

**Comment by danielguardicore** [comment]
Fixed
