### ISSUE TITLE
Map node shows running agent indefinitely

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#2493]
## Describe the bug
If we configure the Agent to have 1 second of `keep_tunnel_open_time`, and the relay closes before the agent is able to send a shutdown signal, the map node shows a running agent.

## To Reproduce
1. Configure the Island to run Depth_4 test
2. Configure `keep_tunnel_open_time` to be one second
3. See map for a frozen running node
4. Check the machine and confirm the agent has actually stopped

## Expected behavior
The map node should be marked as dead but without a relay and shutdown signal, we can't really do it.

# Possible solution
Fix the description in the UI about the `keep_tunnel_open_time` and add a minimum value that will not cause this issue.

## Screenshots
Map after 15 minutes of waiting:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/15820737/198004499-eff8e4af-69ab-4e2a-a05d-b77d95086584.png">

Agent tunneling-10 log:
[infection-monkey-agent-2022-10-26-10-07-30-vkl00k8g.log](https://github.com/guardicore/monkey/files/9868625/infection-monkey-agent-2022-10-26-10-07-30-vkl00k8g.log)

## Machine version (please complete the following information):
 - OS: Windows or Linux

**Comment by mssalvatore** [comment]
This should be resolved by a combination of c88476011 and #2518.

**Comment by shreyamalviya** [comment]
Doesn't show any running agents now
![image](https://user-images.githubusercontent.com/44770317/206441524-cc8c8af4-1aad-4c2e-9ed1-80fda83d4fe8.png)
