### ISSUE TITLE
Investigate custom import of extension modules

### ISSUE THREAD

**Issue by cakekoa** [guardicore/monkey#2570]
# Spike

## Objective
We have been prototyping a plugin architecture in Python that namespaces imports in order to isolate plugin dependencies. However, the prototype does not handle dependencies of extension modules.

Investigate whether or not we can handle extension modules.

## Scope
Determine if _most_ extension modules have no problem an this is a numpy-specific issue.

- [ ] Pydantic
- [ ] pymssql
- [ ] others?

Time remaining: 0d @ilija-lazoroski @cakekoa 

## Output
A report explaining whether or not a solution is possible, and if it is possible, a prototype demonstrating the working solution.

**Comment by ilija-lazoroski** [comment]
From the current investigation, it is discovered that `pymssql` and `numpy` use extension modules and can't be used.  What is interesting is that `pydantic` also uses extension modules but it can be imported. It seems that `pydantic` has pure python implementation and can be compiled using Cython in which case uses extension modules.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/15820737/202675144-43a0e052-26d9-4c9a-9624-297d8359dcdd.png">

**Comment by cakekoa** [comment]
It looks like pymssql is a _cython_ module. My guess is that its import calls are hard-coded into the compiled library, and don't go through our custom import mechanism. That means unless there is a way to intercept that import call, we can't namespace the import.

**Comment by cakekoa** [comment]
[PEP 489](https://peps.python.org/pep-0489/) provides some details on how python loads extension modules
