### ISSUE TITLE
Some UI pages crash if user credentials file can't be found

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#2584]
## Describe the bug
If after running the Agent, the user credentials file in the data directory can not be accessed for some reason, the security report page and the events page crash.

## To Reproduce
1. Run the Island and an Agent.
2. Stop the Island. Delete the user credentials file from the data directory. Run the Island again.
3. Go to the security report page or the events page and see it crash.

## Expected behavior
They shouldn't crash. Not finding the user credentials file should be handled better.

## Screenshots
https://user-images.githubusercontent.com/44770317/201935938-76937533-7950-458b-9ddd-59f57c7acd3d.mp4

## Tasks
- [ ] Fix it (0.5d) @ilija-lazoroski

**Comment by mssalvatore** [comment]
The user's credentials are used to encrypt\decrypt the credentials data stored in mongo. The solution is that all repositories should be reset if credentials are changed.

**Comment by mssalvatore** [comment]
I think the simple solution is to have `AuthenticationService.register_new_user()` publish `IslandEventTopic.CLEAR_SIMULATION_DATA`, `IslandEventTopic.RESET_AGENT_CONFIGURATION`, and `IslandEventTopic.SET_ISLAND_MODE (unset)`.

Arguably, it could also publish `IslandEventTopic.TERMINATE_AGENTS` in case there are any agents running, but that's an edge case I might almost call "unsupported" or "undefined". We could just say, "don't reset the credentials while agents are running, stuff will break."
