### ISSUE TITLE
Update manual run page

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2593]
# Refactor

Manual run page is outdated. We now have the ability to provide multiple servers and the current page doesn't document the options well (what is the second dropdown, what does it do? Which should I pick?)
![image](https://user-images.githubusercontent.com/36815064/202199287-ee74147d-b42d-4b59-a8fb-cefe1c566531.png)

**Comment by mssalvatore** [comment]
I'm reopening this, as it seems that #2593 did not properly resolve the issue. Note that we also need to make this change for the `Run From Island` option.
