### ISSUE TITLE
Security report crashes if no agent is done running

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#2600]
## Describe the bug
If you try to view the security report before any agent is done running, it crashes. You have to wait for one agent to finish running before viewing it.

## To Reproduce
1. Run the Island and Agent.
2. Try viewing the security report before the Agent finishes its run.
3. See it crash.

## Expected behavior
It shouldn't crash.

## Tasks
- [ ] Fix it (0.25d) - @shreyamalviya

**Comment by ilija-lazoroski** [comment]
This happens because we are checking for the latest timestamp. If no event are in the event repository then the security report will crash because we can't get the latest event timestamp.

**Comment by shreyamalviya** [comment]
This also happens if you delete the data or reset the Island and navigate to the security report page without rerunning the Island.
