### ISSUE TITLE
Docker EtE not running

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#2630]
## Describe the bug
Docker EtE not running in Jenkins

## To Reproduce
1. Run Docker EtE and check the console for the error

## Expected behavior
Docker EtE should run

## Screenshots
![image](https://user-images.githubusercontent.com/15820737/203794266-d7a8a00a-9d8e-4682-b0b3-dce28d0b46d6.png)

## Machine version (please complete the following information):
 - OS: Linux

## Possible solution
Probably some update hanged and we just need to run `sudo dpkg --configure -a`

## Tasks

- [ ] Fix it.

**Comment by mssalvatore** [comment]
Fixed. Just had to log in and upgrade docker.
