### ISSUE TITLE
Unable to install AppImage as service

### ISSUE THREAD

**Issue by l3keboy** [guardicore/monkey#2651]
## Describe the bug
When running the command: `./InfectionMonkey-v1.13.0.AppImage service --install --user administrator` as described by the [docs](https://techdocs.akamai.com/infection-monkey/docs/linux#running-the-infection-monkey-as-a-service-on-boot) I get the following error:
```
2022-12-02 12:11:04,358 - report_generation_synchronisation.py:12 -   <module>() - DEBUG - Initializing report generation locks.
usage: monkey_island.py [-h] [-s] [--server-config SERVER_CONFIG]
monkey_island.py: error: unrecognized arguments: service --install --user administrator
```

## To Reproduce
1. Install a Ubuntu Server 20.04
2. Download the .AppImage file from this GitHub Repository (using wget)
3. Follow the other steps in the [getting started page](https://techdocs.akamai.com/infection-monkey/docs/linux#deployment)
4. Run the ['configure as service' steps](https://techdocs.akamai.com/infection-monkey/docs/linux#running-the-infection-monkey-as-a-service-on-boot)

## Expected behavior
Infection Monkey to be installed as a service and be able to start on boot.

## Screenshots
![image](https://user-images.githubusercontent.com/66973798/205280596-6ba69404-f38c-44b9-ab77-a418992b648f.png)

## Machine version (please complete the following information):
 - Linux - Ubuntu Live-Server 20.04.5 LTS
Distributor ID:   Ubuntu
Description:      Ubuntu 20.04.5 LTS
Release:            20.04
Codename:       focal

**Comment by mssalvatore** [comment]
Hi @l3keboy, sorry for the trouble.

That feature hasn't actually been released yet. It looks like it made its way into our documentation before we were ready.

There's a simple workaround, though.

1. Download the [install script](https://raw.githubusercontent.com/guardicore/monkey/develop/build_scripts/appimage/install-infection-monkey-service.sh) and place it in the same directory as your AppImage.
1. Make the install script executable with `chmod u+x install-infection-monkey-service.sh`
1. Run the following command: `sudo APPIMAGE="./InfectionMonkey-v1.13.0.AppImage" ./install-infection-monkey-service.sh --user <YOUR_USERNAME> --install`

**Comment by l3keboy** [comment]
Thanks @mssalvatore! That worked!

Is there also a way to uninstall as service, f.e. when updating to a new version?

**Comment by mssalvatore** [comment]
`sudo APPIMAGE="./InfectionMonkey-v1.13.0.AppImage" ./install-infection-monkey-service.sh --uninstall` should do it.

**Comment by l3keboy** [comment]
Thanks again @mssalvatore!

If you want, you are free to close this issue!
