### ISSUE TITLE
Implement plugin data transformation layer

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2699]
**Is your feature request related to a problem? Please describe.**
The instance that the island expects doesn't fully match the instance rjsf is able to generate. We need additional data translation to account for the limitations of rjsf

**Describe the solution you'd like**
Do the required data traslations/transformations

More context in #2661

## Tasks

- [ ] Remove required fields from plugins. They are not supported until [this](https://github.com/rjsf-team/react-jsonschema-form/pull/3287) is released (0.25d)
- [ ] Remove the plugins from an instance if they are not enabled. Once [this](https://github.com/rjsf-team/react-jsonschema-form/issues/2980) is fixed we'll be able to remove this. Overall data transformation is not a bad solution in this case, because we need to generate a default plugin instance either way. Removing objects we don't need might even be easier than explicitly generating the objects we need. (0.75d)

**Comment by mssalvatore** [comment]
This will be done as part of #2698.
