### ISSUE TITLE
Unmet dependencies while running deployment_scripts

### ISSUE THREAD

**Issue by ashish493** [guardicore/monkey#279]
While running the shell script for deploying linux installation script I get requests of too many dependencies for pip
![Screenshot from 2019-03-13 03-04-46](https://user-images.githubusercontent.com/44671044/54378020-62c84500-4654-11e9-901e-1a1b38d6e3d4.png)

## Expected Behavior
It should automatically install all the dependent packages or either remove them.

## Actual Behavior
Requests of unmet dependencies which takes a lot of time to get corrected.

## Steps to Reproduce the Problem

  1.Running the shell script for deploying monkey on Linux.
  2.Getting error of no module found of pip (which was installed already).
  3.Trying to reinstall pip module.
  4. Getting requests of too many unmet dependencies.

**Comment by ashish493** [comment]
Can be corrected by adding some extra shell commands in the shell script like 
1. sudo apt-get autoremove –purge PACKAGENAME
2. sudo apt-get autoclean

**Comment by Dhayalanb** [comment]
@ashish493 This is not a error in the deployment script

**Comment by ashish493** [comment]
Ok , I will change it but to improve the script we must add extra shell commands to automate the process.
