### ISSUE TITLE
When run the ./monkey/monkey/infection_monkey/build.sh no module named _vendor.six 

### ISSUE THREAD

**Issue by xihajun** [guardicore/monkey#286]
**Describe the bug**
When run the ./build.sh no module named _vendor.six 

**Expected behavior**
Set up easily

**Screenshots**
<img width="833" alt="image" src="https://user-images.githubusercontent.com/25631641/55357920-17bc8780-54c6-11e9-9908-a3b0068f7b41.png">

**Machine version(please complete the following information):**
Linux

**Comment by VakarisZ** [comment]
To build monkey binary with `./build_linux.sh` you need to follow instructions here: https://github.com/guardicore/monkey/tree/develop/monkey/infection_monkey
If you've done it all and still get the same error, please provide your Linux **OS** and version.

**Comment by Dhayalanb** [comment]
@xihajun  I think this is an issue with your pyinstaller
Try running the following `pip install --force-reinstall --no-binary :all: pyinstaller
`

**Comment by xihajun** [comment]
> @xihajun I think this is an issue with your pyinstaller
> Try running the following `pip install --force-reinstall --no-binary :all: pyinstaller`

doesn't work for me

**Comment by VakarisZ** [comment]
`pip install --upgrade setuptools` and this?

**Comment by ashish493** [comment]
Try using apt install -f
It will install the missing dependencies..

**Comment by danielguardicore** [comment]
Does it work for you?

**Comment by ashish493** [comment]
Yes, It worked for me but I also had some error related to broken packages, which I had to fix manually.
