### ISSUE TITLE
White screen on invalid config import

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2920]
## Describe the bug
UI crashes on config import if the configuration is not valid

## To Reproduce
1. Try to import invalid configuration
2. Get white screen

Edit:
I'm not sure how I got this behavior, but it seems like the repository cached empty plugins and that's what it's returning. I'll investigate tomorrow, this might be some kind of local issue

## Expected behavior

Error message should appear

**Comment by cakekoa** [comment]
I have also seen this if I try to import a config with any of these settings missing:
- configuration.propagation.general.maximum_depth
- configuration.advanced.keep_tunnel_open_time

Also an empty configuration.payloads list will cause the screen to go blank when clicking the Payloads tab
