### ISSUE TITLE
Stolen Credentials table clears out when switching to between reports

### ISSUE THREAD

**Issue by cakekoa** [guardicore/monkey#2923]
## Describe the bug
When switching between the Security and Ransomware reports, the Stolen Credentials table of the Security report is cleared out. Switching to a different page (e.g. Configuration) and then back to the Report will cause the report to reload and the Stolen Credentials to be repopulated.

## To Reproduce
1. Use a configuration that steals credentials, such as the one from the credentials_reuse_ssh_key test, or the zerologon test.
2. Run the monkey
3. Observe that the stolen credentials are in the table in the Security report
4. Switch to the Ransomware report
5. Switch back to the Security report
6. Observe that the Stolen Credentials table is now empty

## Expected behavior
The Stolen Credentials table should remain populated.

## Screenshots
> https://user-images.githubusercontent.com/11077625/216450444-e420899f-1486-4733-ab8d-4a83bb70471e.mov

**Comment by VakarisZ** [comment]
If no credentials were stolen then a loading component is permanently there: 
![image](https://user-images.githubusercontent.com/36815064/216635168-89711215-42f2-4e57-b8ba-4f33b429c343.png)
