### ISSUE TITLE
Release build checkmark doesn't work

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2949]
## Describe the bug
The release build does not upload the binary to the storage.

## To Reproduce
1. Build a release binary
2. Check `IS_RELEASE_BUILD` checkmark
3. Launch the build
4. Storage doesn't contain the release binary

## Expected behavior
Storage should contain the release binary or we should remove the checkmark if we don't need the upload anymore

**Comment by mssalvatore** [comment]
@VakarisZ Can we close this since we no longer use "storage"?
