### ISSUE TITLE
Ransomware README line endings on Windows

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2951]
## Describe the bug

The README file that the ransomware module leaves on Windows systems does not use the proper line endings. This results in a README file that's difficult to read.

## To Reproduce
1. Configure the Monkey to use the ransomware payload
2. Run the monkey on a Windows machine
3. View the content of the README.txt file left by the ransomware payload.

## Machine version (please complete the following information):
 - OS: Windows

## Note
The key to this one is probably in the `.gitattributes` file where configure git to not change the file's line endings. I think we do this to simplify the unit tests, but it obviously has some ill effects at runtime.

**Comment by shreyamalviya** [comment]
I wasn't able to reproduce this.

**Comment by ilija-lazoroski** [comment]
I am able to reproduce it 
![image](https://user-images.githubusercontent.com/15820737/217766131-c5a0e442-e3da-4e8c-86cf-8c2103c125df.png)

**Comment by ilija-lazoroski** [comment]
It seems that Notepad before Windows 10 1809 (or everything before 2018) doesn't support Unix LF.

https://devblogs.microsoft.com/commandline/extended-eol-in-notepad/
