### ISSUE TITLE
Times in Island UI reported in different timezones

### ISSUE THREAD

**Issue by cakekoa** [guardicore/monkey#2956]
## Describe the bug
In some parts in the Island UI, times are listed in browser's local time zone. In other parts, times are listed in the server's timezone.

## To Reproduce
1. Run a scenario and look at the reports. See the screenshots.

## Expected behavior
I would expect all times to be listed in the same timezone, preferably the browser's timezone

## Screenshots
As one example, here we see the agent start time reported in the server's timezone:
> ![Screen Shot 2023-02-08 at 4 26 49 PM](https://user-images.githubusercontent.com/11077625/217656099-189512bc-f382-4670-b33e-63493c792131.jpg)

And here, we see that same start time reported in the browser's timezone:
> ![Screen Shot 2023-02-08 at 4 26 16 PM](https://user-images.githubusercontent.com/11077625/217656102-64b0bd21-e228-407e-8823-7c366f39aa4d.jpg)

**Comment by mssalvatore** [comment]
Fixed by #2960
