### ISSUE TITLE
Duplicate tunneling issues in the Security report

### ISSUE THREAD

**Issue by cakekoa** [guardicore/monkey#2957]
## Describe the bug
The Security report can show duplicate tunneling issues for a single machine

## To Reproduce
I noticed this behavior while running the agent several times _without clearing the data between runs_.

1. Configure the Monkey for depth_3_a test
2. Run the monkey
3. After the run completes, run the monkey again without clearing simulation data (this step can be repeated)
4. Look at the Security report and observe duplicate tunneling entries

## Expected behavior
Only unique tunnel issues are displayed

## Screenshots
> ![Screen Shot 2023-02-08 at 4 23 26 PM](https://user-images.githubusercontent.com/11077625/217658094-edf91d0b-abb8-4d38-afcf-b1b90ae6d0f9.jpg)

**Comment by mssalvatore** [comment]
Resolved by de00a937c
