### ISSUE TITLE
Prototype pluggable events

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2966]
# Spike

## Objective

Put together a prototype that allows events to be imported dynamically from plugins at runtime in the Island, Agent, and Plugin code.

## Scope
- [x] Island can import events from plugins
- [x] Agent can import events from plugins
- [x] The Plugin can import and publish custom events
- [x] The Agent can receive events from the plugin and forward them to the Island
- [x] The Island can store and retrieve custom events

## Output

A branch with a rough prototype.

## Considerations

1. Plugins will need to declare their custom events in their manifest files
2. In order for an object to be sent between processes, it must be importable from both processes
3. Should plugin's have a `__init__.py` file to make it simpler to import custom events?

**Comment by mssalvatore** [comment]
See the branch named `prototype-custom-events` for the prototype.

**Comment by cakekoa** [comment]
See the prototype work on the `prototype-custom-events` branch. It creates a `CustomEvents` Credentials Collector plugin that uses a custom `MessageEvent` event. The plugin sends the event, and the Island serializes it:

![screenshot_2023-06-05_at_8 41 22_am](https://github.com/guardicore/monkey/assets/11077625/a3c5e79c-5827-4182-937d-9fa321e548f1)

One thing that hasn't been considered is how or whether or not to encrypt the event data when storing it in the event repository.
