### ISSUE TITLE
"Not Found" page not working

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#3073]
## Describe the bug
On the Island, if you try going to a URL that doesn't exist, the "Not Found" page isn't shown. It's just blank.

## To Reproduce
1. Run the Island
2. Go to a URL that doesn't exist

## Expected behavior
The "Not Found" page should be shown.

## Screenshots

https://user-images.githubusercontent.com/44770317/223967799-c0e487e4-8298-4a05-a2da-35e5757c967d.mp4

**Comment by ilija-lazoroski** [comment]
![image](https://user-images.githubusercontent.com/15820737/223969210-2f5d6736-6dec-498d-8da9-571a7a694d66.png)
