### ISSUE TITLE
Ransomware: partial file encryption

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#3100]
According to [this report](https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-061a#:~:text=Royal%20ransomware%20uses%20a%20unique%20partial%20encryption%20approach%20that%20allows%20the%20threat%20actor%20to%20choose%20a%20specific%20percentage%20of%20data%20in%20a%20file%20to%20encrypt.), the Royal ransomware has a unique file encryption program that only encrypts a specific percentage of data in a file, which helps evade detection.

This would be a good addition to our ransomware payload. 

Questions to answer:
1. What kind of encryption algorithm(s) can we use this with?
1. What kind of encryption algorithm(s) can we _safely_ use this with?
1. Do we need a minimum percentage value?
1. What should the recommended percentage value be? At what percentage would most security solutions be triggered?

**Comment by cakekoa** [comment]
Moved to guardicode/ransomware-payload#3
