### ISSUE TITLE
Invalid IP values can be submitted in configuration

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#3225]
## Describe the bug
The hostname validation is buggy which is why invalid values can be submitted in the configuration.

## To Reproduce
1. Run the Island
2. Try adding a simple string like "aaaa" in scan target list
3. See that it gets submitted successfully

## Expected behavior
It shouldn't be submitted successfully.

The logic in `validate_hostname()` needs to be modified. UTs also need to be added for it.

**Comment by mssalvatore** [comment]
Strings can be valid hostnames. This is acceptable input. However, we have found a small bug. See #3231.
