### ISSUE TITLE
Weirdly formatted InnoSetup window

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#3227]
## Describe the bug
Trying to install the MSI again when it's already installed results in this weirdly formatted window:
![image](https://user-images.githubusercontent.com/44770317/231728501-f34a3d52-2a95-4d75-8d99-c61f11491c3f.png)

## To Reproduce
1. Install MSI
2. Try to install it again

## Expected behavior
A well-formatted window with clear information.

**Comment by ilija-lazoroski** [comment]
This is what I see on GCP machine: 
<img width="645" alt="image" src="https://user-images.githubusercontent.com/15820737/231743866-0463019f-177d-4c09-a41a-1aa646b8bc64.png">

**Comment by ilija-lazoroski** [comment]
Hey @shreyamalviya, can you share your windows version and display properties? I have tried these on couple different Windows version with a lot of display variants, couldn't reproduce it.

**Comment by shreyamalviya** [comment]
**OS details**
Edition: Windows 10 Enterprise
Version: 21H2
OS build: 19044.2728
Experience: Windows Feature Experience Pack 120.2212.4190.0

**Display details**
Size of text, apps, and other items: 250% (Recommended)
Resolution: 3840 x 2400
Orientation: Landscape

**Comment by shreyamalviya** [comment]
From island-windows-251 on the original zoo:
![image](https://user-images.githubusercontent.com/44770317/232476275-c4bc3c6c-8c76-48a2-b832-18d41d60b2fb.png)

**Comment by cakekoa** [comment]
Thanks Shreya. I was finally able to get the issue to manifest with the following settings (applicable to Mac only):

![Screenshot 2023-04-17 at 10 12 12 AM](https://user-images.githubusercontent.com/11077625/232515948-7f6577be-ee98-4081-9268-e02b461414dd.jpg)
