### ISSUE TITLE
PBAs with unsupported local commands cause the monkey to crash

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#323]
**Describe the bug**
When the monkey fails in running a PBA, it crashes.

**To Reproduce**
1. Configure the Monkey with the `wall "say something"` PBA
2. Run the monkey on an Ubuntu Server 14.04 (in which `wall` required input from `stdin`, unlike the newer versions of wall which could take a message)
3. The monkey will end its executing early and die
4. In the monkey's local log, you'll see a stack trace from the main startup function 

**Expected behavior**
The monkey ought to report the failure and continue with normal execution. A failed PBA should be reported, but not terminate the monkey. 

**Machine version**
 - Island: whatever
 - Victim: Ubuntu Server 14.04 in AWS

**Comment by VakarisZ** [comment]
I've tried various commands that failed on windows/linux locally but couldn't reproduce :( Can you please add logs?

**Comment by ShayNehmad** [comment]
unable to reproduce
