### ISSUE TITLE
Support PPK in SSH Credential Collector

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#3236]
**Is your feature request related to a problem? Please describe.**
SSH Collector should support PPK files. It should collect it from a Windows machine convert it to PEM and store it so it can be used to ssh into a machine.

In the below picture, a converted PEM is used to log into an AWS instance. (Note: The instance is not communicating back because some more networking needs to be set)

<img width="499" alt="image" src="https://user-images.githubusercontent.com/15820737/233429118-c78d3b04-221b-4a25-a47b-138946b5b8f7.png">

**Comment by cakekoa** [comment]
Moved to guardicode/ssh-credentials_collector#1
