### ISSUE TITLE
URI sanitizer removes legal URIs

### ISSUE THREAD

**Issue by ordabach** [guardicore/monkey#3318]
## Describe the bug
Although the URI regex test value and the expected result are equal, the condition checking if they are NOT equal returns true.

## Screenshots
![Screenshot 2023-05-08 at 16 55 53](https://user-images.githubusercontent.com/127864008/236844468-3998e388-fc6e-472f-8882-8859f89d7943.jpg)

**Comment by mssalvatore** [comment]
Fixed by https://github.com/guardicore/monkey/commit/c2795ac34a0ec56dbd3e3b027c7ce2aa567eb249
