### ISSUE TITLE
Populate credentials in DAL model file

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#332]
Populate the `Creds` class in monkey_island/cc/models/creds.py with its actual data fields, extract relevant logic to model class:

- `add_credentials_to_node`
- `add_credentials_to_monkey`
- `resources/monkey.py:monkey:post`

and add unit tests in models/test_creds.py

**Comment by mssalvatore** [comment]
The credentials subsystem has been entirely replaced. Closing.
