### ISSUE TITLE
Plugin installation screen UI Mockup

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3419]
# Spike

## Objective
Create a mockup for the UI described in #3418.

## Output
After a team review, add the mockup to issue #3418 (0.25d)

**Comment by ordabach** [comment]
![Screenshot 2023-06-15 at 10 37 07](https://github.com/guardicore/monkey/assets/127864008/5f8f1b6e-9b64-4929-9b4f-81c57d3b51cf)

**Comment by ordabach** [comment]
![image](https://github.com/guardicore/monkey/assets/127864008/c3fae677-c8d5-4739-b0c3-f66884be594b)

**Comment by ordabach** [comment]
![Screenshot 2023-06-15 at 17 46 24](https://github.com/guardicore/monkey/assets/127864008/b9874757-a350-4fab-91c5-214e34757d62)
