### ISSUE TITLE
Store Terraform state in the cloud

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#3552]
**Is your feature request related to a problem? Please describe.**
In order for anyone on the team to be able to create instances, images, or firewall rules using Terraform on any of the zoo projects we need to store the Terraform state somewhere in the cloud.

**Describe the solution you'd like**
Investigate and decide on what is the best solution to use. I think we can use Amazon S3 Buckets to do that.

**Comment by ordabach** [comment]
Do we need a drift detection for it?
