### ISSUE TITLE
Improve descriptions in plugin table

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3666]
**Is your feature request related to a problem? Please describe.**
Better description of a plugin. User will likely want to read more about the plugin before downloading it. The small text with unclickable links in the tooltip is not great for this 

**Describe the solution you'd like**
There are various path:
a. Try to use Collapsible component as in https://mui.com/material-ui/react-table/#collapsible-table). Table is completely different component. To implement such thing in the data grid we need to override the "row" slot https://mui.com/x/api/data-grid/data-grid/#DataGrid-slots-null. 
b. Try to make more space for description and make it expandable
c. Make the tooltip more advanced and clickable

**Comment by ordabach** [comment]
You can implement rich tooltip using these helpful resources:
https://mui.com/material-ui/transitions/
https://mui.com/material-ui/react-popover/
https://github.com/tailwindlabs/headlessui/discussions/425#discussioncomment-5117609
https://codesandbox.io/s/d8llw?file=/src/App.js
https://codesandbox.io/s/q558p?file=/src/App.js:38-48

**Comment by VakarisZ** [comment]
Follow up: https://github.com/guardicore/monkey/issues/3697
