### ISSUE TITLE
Steal browser credentials from other users on Windows

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#3671]
## Desription

#3426 introduces a Chrome credentials collector plugin. On Windows, this only attempts to steal credentials from the current user. Update the plugin's Windows logic to also attempt to steal browser credentials from other users on the system. This will require looking into DPAPI. #3398 may have more useful information.

**Comment by cakekoa** [comment]
Moved to guardicode/chrome-credentials_collector#1
