### ISSUE TITLE
UI Styling - MUI Library

### ISSUE THREAD

**Issue by ordabach** [guardicore/monkey#3679]
# Spike

## Objective
Team should get familiar with [MUI](https://mui.com/material-ui/) lib (v5) and how it can be integrated with the Next.js (v13+) framework.
[MUI v5 integration](https://github.com/mui/material-ui/tree/master/examples/material-ui-nextjs-ts)

## Goal
- [x] Vakaris
- [x] Ilija
- [ ] Shreya
- [ ] Mike
- [x] Kekoa

## Scope
1-1.5 days

**Comment by cakekoa** [comment]
[This video](https://www.youtube.com/watch?v=o1chMISeTC0) linked from the [Learn](https://mui.com/material-ui/getting-started/learn/) page is pretty good for seeing "MUI in action"
Also this was the only nextjs-specific page I found: https://mui.com/material-ui/guides/next-js-app-router/
