### ISSUE TITLE
UI State Manager - Redux Toolkit

### ISSUE THREAD

**Issue by ordabach** [guardicore/monkey#3681]
# Spike

## Objective
Explore the [Redux Toolkit](https://redux-toolkit.js.org/) lib along with its [RTK Query](https://redux-toolkit.js.org/rtk-query/overview) tool.

## Scope
- Time: 1.5-2 days
- How it can be integrated with the Next.js (v13+) framework and NextAuth.js

**Comment by VakarisZ** [comment]
Added in #3896
