### ISSUE TITLE
UI rjsf alternative

### ISSUE THREAD

**Issue by ordabach** [guardicore/monkey#3683]
# Spike

rjsf is not very intuitive to use and has some complexity.
We don't even use a quarter of the lib options.

## Objective
Find an alternative solution to the rjsf lib.
The target is to reduce the complexity.
We may also decide to implement one that will fit our purposes.

## Scope
1-1.5 days

## Output
Pros and cons of each lib/approach

**Comment by shreyamalviya** [comment]
> Maybe since the plugin migration is doe we can simplify the UI.
We still have hard-coded fingerprinters.

**Comment by VakarisZ** [comment]
Additional complexity is in plugin display component (`PluginSelectorTemplate`). It's coupled to global config through `PLUGIN_SCHEMA_PATH`. I think this stems from the fact that our state management in tabs is done poorly.

**Comment by VakarisZ** [comment]
Related: #3887

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/3770

**Comment by VakarisZ** [comment]
This got split up into specific actions to take in the above issues, closing. If @ordabach wants to suggest specific alternatives open new issues with more details
