### ISSUE TITLE
UI Tests

### ISSUE THREAD

**Issue by ordabach** [guardicore/monkey#3685]
# Spike

## Objective
- Unit tests: Find a lib that will be used for unit tests (e.g.: jest, karma, mocha, etc)
- App tests: Find a framework that will be used to test our app (e.g.: cypress, selenium, testim.io, etc)

## Scope
1-2 days

## Conclusions
Jest & Cypress

**Comment by ordabach** [comment]
@ilija-lazoroski 
https://www.lambdatest.com/blog/playwright-vs-selenium-vs-cypress/

**Comment by VakarisZ** [comment]
## Article: 

![image](https://github.com/guardicore/monkey/assets/36815064/e89feb71-fa82-4bcf-b2ee-d087618ddf77)

## Reality

![image](https://github.com/guardicore/monkey/assets/36815064/55a2f0aa-cfb9-43fa-bc4a-d410456a3aa3)
