### ISSUE TITLE
UI crashes when searching plugins

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#3692]
## Describe the bug
Typing anything in to the search bar on the plugins page causes the UI to crash (tested with MSI).

## To Reproduce
1. Run Island
2. Go to Plugins page
3. Try to type something in the search bar

## Expected behavior
Shouldn't crash, should search plugins like it's expected to

## Screenshots
[bug.webm](https://github.com/guardicore/monkey/assets/44770317/89d3bbe0-7871-447e-992f-878c3aa9f9ee)

![image](https://github.com/guardicore/monkey/assets/19957806/eb32a2e4-9369-48a0-9dc0-ffbd03fe22d4)

<img src="https://github.com/guardicore/monkey/assets/44770317/b67cd146-a816-4728-857f-cf887892c5cf" width=300>

**Comment by mssalvatore** [comment]
This is also reproducible with AppImage.
