### ISSUE TITLE
Login page error messages are inconsistent

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#3702]
## Describe the bug
The error messages shown on the login page in the UI are inconsistent for different cases. See video below.

## To Reproduce
1. Run Island
2. Input wrong credentials on the login page and submit, see error message
3. Input only username on the login page and submit, see error message
4. Input only password on the login page and submit, see error message
5. Input nothing on the login page and submit, see error message

## Expected behavior
Consistent and specific error messages for each case, or at the minimum, one consistent general error message for all cases.

## Screenshots

[bug.webm](https://github.com/guardicore/monkey/assets/44770317/0fdeee1b-924f-4f86-b940-dfc929e26931)

**Comment by rahul0x00** [comment]
@shreyamalviya 
Hi, Shreya I'd like to work on this issue

**Comment by rahul0x00** [comment]
[Screencast_10_16_2023_10:35:19_PM.webm](https://github.com/guardicore/monkey/assets/104289350/2f8071c0-5ba2-44f8-8ad1-01fda540c425)

**Comment by rahul0x00** [comment]
> Hi, @shreyamalviya
> 
> The username and passwords fields are not set to "required", setting them required fixes the issue. By making the both input fields as required, the system will enforce users to input a username & password before they can submit the login form. This will ensure that users cannot leave the username field empty while entering a password or any other scenario, and it will lead to a more consistent and expected behavior.

should i push this changes?

**Comment by rahul0x00** [comment]
If i'm not wrong this is the code responsible for this login page,right?
https://github.com/guardicore/monkey/blob/develop/monkey/monkey_island/cc/ui/src/components/pages/LoginPage.js

**Comment by shreyamalviya** [comment]
@rahul0x00 can you open a PR with the changes you're suggesting? We can discuss it there.

**Comment by rahul0x00** [comment]
@shreyamalviya 
I've just opened the PR, Please feel free to review and provide feedback.
