### ISSUE TITLE
Unused parameter in Jenkins job that builds all Islands 

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#3716]
## Description
The "island_all_platforms" job on Jenkins has a parameter `BUILD_MONKEY_BINARIES` which doesn't do anything if enabled.

Either remove the parameter and update the job to specify that last successful Agent binaries will be used, or fix the job to build the binaries if the parameter is enabled.

**Comment by ilija-lazoroski** [comment]
I deleted this parameter as we don't need it. All separate island jobs are taking the last successful agents.
