### ISSUE TITLE
Plugin SDK Library

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3725]
# Spike

## Objective

In order for 3rd parties to be able to develop or contribute to plugins, they need a tool set that allows them to do so. We should consider breaking out components from `common` and `infection_monkey` into one or more Python libraries so that developers can develop plugins independently of the rest of the platform. Ideally, we want as few libraries as possible, though they should be as cohesive as possible.

## Output
Create a plan for how to divide up our monolith into libraries that can form a plugin SDK.

**Comment by shreyamalviya** [comment]
https://docs.google.com/document/d/1hAWPvYrPzChym2TfMevEJ2t6Srcwk5IQEHzR2UuRKXo/edit?usp=sharing

**Comment by shreyamalviya** [comment]
[Plugin SDK dependency diagram](https://drive.google.com/file/d/1KTrOcWd8jPrmOLu_3mkeGPAfx-OTjfyc/view?usp=sharing)
