### ISSUE TITLE
Extract agent events repository

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3798]
## Goal
Extract agent events out of the monorepo and into its own repository.

## Motivation
In order for 3rd-party developers to develop their own plugins efficiently, plugins' dependencies should be installable with `pip`. Extracting the agent events into its own repository as we did with [monkeytypes](https://github.com/guardicode/monkeytypes) helps enable this.

## Details
- A "best effort" approach will be taken to preserve the git history of the files that are moved. See monkeytypes for an example
- The script and artifacts used to migrate monkeytypes is attached below for reference
- Boilerplate for setting up the new project can be created from the [infection monkey cookiecutter template](https://github.com/guardicode/infection-monkey-cookiecutter).
- [cruft](https://pypi.org/project/cruft) should be used to apply the cookiecutter to the migrated project
- Wait for the completion of https://github.com/guardicore/monkey/issues/3732 before performing the migration.
- The new package will be published to PyPI so it can be installed via `pip`. @mssalvatore can help.

### Attachments
[extract-monkeytypes.zip](https://github.com/guardicore/monkey/files/12929661/extract-monkeytypes.zip)

**Comment by shreyamalviya** [comment]
https://github.com/guardicode/monkeyevents
