### ISSUE TITLE
Infection Monkey https://<server-ip>:5000 not accessible

### ISSUE THREAD

**Issue by omaemaru** [guardicore/monkey#380]
**Describe the bug**
Checking on the services I found that the monkey island service was not running. 

● monkey-island.service - Monkey Island Service
   Loaded: loaded (/lib/systemd/system/monkey-island.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-07-15 15:32:06 IDT; 1 day 19h ago
  Process: 5314 ExecStart=/var/monkey/monkey_island/service/systemd/start_server.sh (code=exited, status=1/FAILURE)
 Main PID: 5314 (code=exited, status=1/FAILURE)

Jul 15 15:32:06 ubuntu start_server.sh[5314]:   File "/usr/lib/python2.7/httplib.py", line 453, in begin
Jul 15 15:32:06 ubuntu start_server.sh[5314]:     version, status, reason = self._read_status()
Jul 15 15:32:06 ubuntu start_server.sh[5314]:   File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
Jul 15 15:32:06 ubuntu start_server.sh[5314]:     line = self.fp.readline(_MAXLINE + 1)
Jul 15 15:32:06 ubuntu start_server.sh[5314]:   File "/usr/lib/python2.7/socket.py", line 480, in readline
Jul 15 15:32:06 ubuntu start_server.sh[5314]:     data = self._sock.recv(self._rbufsize)
Jul 15 15:32:06 ubuntu start_server.sh[5314]: socket.timeout: timed out
Jul 15 15:32:06 ubuntu systemd[1]: monkey-island.service: Main process exited, code=exited, status=1/FAILURE
Jul 15 15:32:06 ubuntu systemd[1]: monkey-island.service: Unit entered failed state.
Jul 15 15:32:06 ubuntu systemd[1]: monkey-island.service: Failed with result 'exit-code'.

**To Reproduce**
1. Import OVA
2. Access https://<server-ip>:5000
3. Not accessible, getting a "ERR_EMPTY_RESPONSE" error

**Expected behavior**
To work

**Machine version(please complete the following information):**
 - OS: Ubuntu 16.04.6 LTS

**Comment by danielguardicore** [comment]
I think we fixed this as part of 1.7, in #463 
Can you try this out again?
