### ISSUE TITLE
Invalid configuration once plugin is deleted

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3859]
## Describe the bug
Configuration is not loaded if enabled plugin got deleted

## To Reproduce
1. Enable a plugin in configuration
2. Remove the plugin
3. To to the configuration
4. Configuration error

## Expected behavior
UI shouldn't break. It should either prompt for configuration reset, reset it automatically or just remove the config value of the removed plugin

**Comment by shreyamalviya** [comment]
Duplicate of #3752
