### ISSUE TITLE
Limit log file size

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#386]
## Expected Behavior
The monkey and the monkey island should limit the log size, and maybe use rotating logs. 

## Actual Behavior
The log is just one file and can get quite long.

**Comment by danielguardicore** [comment]
We should only do this for the Island, the Monkey should keep a full and accurate log.

**Comment by VakarisZ** [comment]
I'd prefer solve it by removing redundant info rather than rotating logs.

**Comment by danielguardicore** [comment]
@VakarisZ What do you mean by redundant information? As in going up a logging level or?

**Comment by danielguardicore** [comment]
Island already rotates. Monkey shouldn't rotate.
