### ISSUE TITLE
UI: mark newly added hosts

### ISSUE THREAD

**Issue by itsikkes** [guardicore/monkey#4]
When viewing the admin page, mark in some way new monkeys that were just added so it will be easier to notice

**Comment by Fak3** [comment]
We should decide when to unmark the new monkey - when it get selected, or after timeout, or some other way?

**Comment by danielguardicore** [comment]
I think if a new monkey shows up in the UI, we should highlight it (bold with color or something?) untill some set timeout say, 15 seconds
