### ISSUE TITLE
Add a loading component to reset request

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#417]
## Expected Behavior
After request to reset the server might take time to respond, so the UI should render a Loading component (like ReportLoader).

## Actual Behavior
The page just "hangs" and it's not clear to the user that a request went through. 

## Steps to Reproduce the Problem

  1. Send a reset request while the server is doing something else (report generation for example or even stuck on a breakpoint)
  1. See that it hangs

**Comment by VakarisZ** [comment]
Checkmarks still linger after loading is done 
![image](https://user-images.githubusercontent.com/36815064/82568976-442ed980-9b88-11ea-82ed-c23f0eb2986c.png)
