### ISSUE TITLE
execution of monkey on host gives error

### ISSUE THREAD

**Issue by 007scorpio** [guardicore/monkey#43]
ImportError: No module named Queue
Failed to execute script pyi_rth_twisted

**Comment by acepace** [comment]
Hey, it looks like you tried to compile the Monkey yourself, or is this running the python code?
If the former, what version of PyInstaller are you running?

**Comment by 007scorpio** [comment]
I did not compile it myself... i used the deb file with the command: Sudo -H apt-get install -f monkey_island.deb. 

Thanks

**Comment by acepace** [comment]
Alright, in order to repro the problem, can you give me the Windows version you're running on?

**Comment by 007scorpio** [comment]
windows 8.1 pro (did not work)
windows 7 ( did not work)

Thank You

**Comment by 007scorpio** [comment]
ok i fixed it

**Comment by acepace** [comment]
What did you analyse as the root cause + solution?

**Comment by 007scorpio** [comment]
Oh ok the problem has to do with twisted. so i uninstall monkey_island and did: "pip install twisted --upgrade" so that it fix the monkey during compilation into .exe
