### ISSUE TITLE
Zero Trust AWS IAM roles PE + S3 access test

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#439]
Check for AWS IAM roles on the EC2 machine and check for dangerous roles. Based on [Rhino Security Labs' research](https://github.com/RhinoSecurityLabs/Security-Research/blob/master/tools/aws-pentest-tools/aws_escalate.py).

- [ ] DDR

**Comment by ShayNehmad** [comment]
We chose a different direction with #519, however this might still be useful (maybe to integrate into ScoutSuite even). Leaving open for now

**Comment by mssalvatore** [comment]
This doesn't fit Infection Monkey's current mission.
