### ISSUE TITLE
Duplicate credentials added to configuration.

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#443]
**Describe the bug**
Each monkey run that gathers credentials adds them to credential list without checking if they already exists. This results in monkey brute-forcing the same credentials multiple times.

**To Reproduce**
1. Run monkey on machine with credentials and allow mimikatz to gather passwords or hashes. 
2. Run monkey again on the same machine and it will gather same passwords/hashes again.

**Expected behavior**
Before adding credentials monkey island should check for already existing ones

**Screenshots**
![image](https://user-images.githubusercontent.com/36815064/65257790-74f6d480-db0a-11e9-8082-26360312acf6.png)

**Comment by danielguardicore** [comment]
The addition of credentials happens at the island, so this should be fixed on the Island side.
But agreed
