### ISSUE TITLE
Mimikatz dll outdated

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#471]
**Describe the bug**
Mimikatz credential collection seems to fail collecting credentials on windows 10. Not sure which mimikatz version is forked [here](https://github.com/guardicore/mimikatz/tree/1.1.0) (1.1 ?) but the latest one is 2.2 and it manages to collect win10 credentials.

**Comment by khast3x** [comment]
Hey @VakarisZ ,

I was looking into replacing with a newer Mimikatz version (as documented [here](https://github.com/guardicore/monkey/blob/develop/monkey/infection_monkey/readme.txt)) but it seems the Guardicore team uses a [modified Mimikatz version](https://github.com/guardicore/mimikatz/commit/2584e1666da75584ac9e9e7aaf2b586b3eea16bc).  

I'm guessing they'll have to apply to same edits to the newer Mimikatz code to integrate it.

**Comment by VakarisZ** [comment]
Yes. Hopefully we can do it on a following release

**Comment by khast3x** [comment]
Hello,

I was playing with [pypkatz](https://github.com/skelsec/pypykatz) and was thinking that it would be a nice fit for fixing this issue.  

Furthermore, doing the hash crypto operations on the Island and sending them back to the Monkey means less noise in the field too.  
I don't have the means to contribute the appropriate PR but I hope the idea can help.  

This might also fit with the ongoing work for #514.

Cheers!

**Comment by VakarisZ** [comment]
Hmmm... Interesting. We'll be taking a look, thanks!

**Comment by ShayNehmad** [comment]
We decided to go with pypykatz #583

**Comment by khast3x** [comment]
Glad the suggestion helped, looking forward to the update. Cheers
