### ISSUE TITLE
Missing .deb in release package

### ISSUE THREAD

**Issue by khast3x** [guardicore/monkey#474]
Hello,

The `.deb` packages have not been included since 1.6. Could you please attach them? This would also enable bumping the version in the Dockerfile.

Cheers!

**Comment by ShayNehmad** [comment]
Hi @khast3x, 
The `.deb` package and the new Docker image for 1.7.0 are both available for download via [the Infection Monkey website](infectionmonkey.com). On our GitHub release assets, we provide the compiled Monkey agents and the binaries required to compile the Monkey agents - not the Island as a .deb or other release which we do provide via our website. 

If you wish to run the island from source you can do so - see `monkey/monkey_island/readme.txt`

**Comment by khast3x** [comment]
I'll check it out, thanks!
