### ISSUE TITLE
The documentation for running from source doesn't tell to add chmod +x to the binaries

### ISSUE THREAD

**Issue by liad-guardicore** [guardicore/monkey#487]
**Describe the bug**
The documentation for running from source doesn't tell to add chmod +x to the binaries

This is both the binaries, and also the .sh files

**Comment by shivank1234** [comment]
Ya, This is something I faced problems with at the start...

**Comment by VakarisZ** [comment]
If you're talking about monkey binaries like "monkey-linux-64" that's not exactly "running from source". Running monkey from source would be python ./infection_monkey.py

**Comment by ShayNehmad** [comment]
Referenced in #494
