### ISSUE TITLE
MITRE ATT&CK - Improve Reporting UX and UI

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#491]
**Is your feature request related to a problem? Please describe.**

The MITRE ATT&CK report is comprehensive but the UI itself isn't friendly at all: 
 
![image](https://user-images.githubusercontent.com/48879847/68878806-ff297680-0710-11ea-827f-623e4eec5f5c.png)

**Describe the solution you'd like**

There are 2 key decisions to make about the solution: 
* ATT&CK report UI - How do we want it to look? The current leading option is to replicate the Matrix (Like in the configuration) with colours that indicate the status of each technique. When a technique is clicked the specifics of that techniques is displayed to the user (possibly in a modal or scrolling to the information which will expand). Other options seem to not speak the ATT&CK language as well. 
* ATT&ACK report location - Where do we want it to be? It might be nice to have 3 report tabs under a new "reports" section: the Security report, the Zero Trust report, and the MITRE report (we may want to separate the security report into more sections - maybe create a separate segmentation report). Alternatively, it can stay in the Security report but move higher (and we add a clickable table of contents to the Security report since it's getting quite long). NEED TO MAKE A CALL HERE

**Comment by acepace** [comment]
> ATT&CK report UI - How do we want it to look? The current leading option is to replicate the Matrix (Like in the configuration) with colours that indicate the status of each technique. When a technique is clicked the specifics of that techniques is displayed to the user (possibly in a modal or scrolling to the information which will expand). Other options seem to not speak the ATT&CK language as well.

I agree on that. It needs to look like the ATT&CK matrix visually, if not identical.
