### ISSUE TITLE
Add Kali distribution

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#498]
**Is your feature request related to a problem? Please describe.**
Installing on Kali doesn't work using the .deb installer. 

**Describe the solution you'd like**
1. Option for Kali package as a distribution.
2. Monkey preinstalled on Kali would be a nice second step. 

**Describe alternatives you've considered**
Currently installing via Docker is a workaround.

**Comment by rish9101** [comment]
Hi, I would like to give this issue a try. Can I take this up?

**Comment by ShayNehmad** [comment]
Closed by @danielguardicore in #553
