### ISSUE TITLE
Download new version button leading to an error page in lambda

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#504]
## Describe the bug
Pressing the "download new version here" button should lead to a working download page. 

## To Reproduce
1. Configure the Monkey Island with an older version
2. Run the monkey island
3. Click on "Download here"
4. Get error page

## Expected behavior
I think this should just redirect to infectionmonkey.com to get a new binary from the email - best case scenario we get a dedicated download page which gets the env via URL param (still want an email I think).

## Screenshots
This is the error page: 

URL: `https://updates.infectionmonkey.com/?deployment=develop&monkey_version=1.6.3-dev&is_download=true`

```
{"stackTrace": [["/var/task/lambda_function.py", 172, "lambda_handler", "res = handle_get(body, params, real_context)"], ["/var/task/lambda_function.py", 133, "handle_get", "raise generate_redirect_response(download_link)"]], "errorType": "https://github.com/guardicore/monkey", "errorMessage": "MonkeyRedirect"}
```

**Comment by danielguardicore** [comment]
Fixed, solved in guardicore backend 
![image](https://user-images.githubusercontent.com/15857396/77890636-79016d00-7278-11ea-9b13-ef88bfe02caf.png)
