### ISSUE TITLE
"Expert Mode" page for configuration

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#526]
**Is your feature request related to a problem? Please describe.**
The "usual" configurable parts of the Monkey (such as IP scan list) and the very advanced features (like OS collectors and TCP Timeout) are in the same configuration and given "equal visual importance". 

**Describe the solution you'd like**
Move all non-trivial parts of the configuration to an "expert mode"/"advanced configuration" page which will be separate from the regular configuration page. 

**Describe alternatives you've considered**

* Moving everything into "internal"
* Keeping the situation the same

**Comment by VakarisZ** [comment]
Another possible implementation would be to add a button-switch (like in ATTACK report "show list of techniques") to toggle expert mode on/off. Expert mode would just "unhide" all config options, while standard mode would have some of them hidden (this allows us to keep info sorted by tab).

**Comment by ShayNehmad** [comment]
Included in #637
