### ISSUE TITLE
How to install infection Monkey on Kali linux

### ISSUE THREAD

**Issue by momaydopod** [guardicore/monkey#529]
I downloaded file (monkey_island.ded) on kali linux

Running command suscessfully "sudo dpkg -i monkey_island.deb
sudo apt-get install -f"

And Open bowser go to https://<server-ip>:5000   page not show anything

**Comment by ShayNehmad** [comment]
Hi @momaydopod, I'm sorry you're having issues with deployment. 
Can you post your server details (run `uname -a`) and the installation logs (run `sudo systemctl monkey-island.service status`)? These details might help us to figure out what went wrong.
