### ISSUE TITLE
Make telemetry console autoscroll to last line

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#538]
**Is your feature request related to a problem? Please describe.**
When looking at the map page, it's unclear if the telemetry console is moving or not.

**Describe the solution you'd like**
I'd like for the textbox to:

1. Autoscroll to last line
2. Write current line and total amount like `[11/150]`

**Describe alternatives you've considered**
Scrolling manually works, but it's much less smooth.

**Comment by Parth1811** [comment]
Hey @ShayNehmad, I would like to work on this one. How should I get started?
