### ISSUE TITLE
ATT&CK report throws UI errors

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#539]
### With this situation:
![image](https://user-images.githubusercontent.com/36815064/73191406-1ed91400-4130-11ea-821a-6023b6348faa.png)
### We get this error upon inspecting certain techniques on ATT&CK report
![image](https://user-images.githubusercontent.com/36815064/73191521-4af49500-4130-11ea-8848-624bb131cf29.png)

## To Reproduce
Use monkeyzoo on gcp

**Comment by ShayNehmad** [comment]
Same as #577 , marking as duplicate
