### ISSUE TITLE
Empty fields in configuration

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#540]
## Describe the bug
Configuration allows submission of empty fields, but in monkey they get registered as values of `None` and might throw errors. 
I found the following error, but more fields should be checked.
### Config:
![image](https://user-images.githubusercontent.com/36815064/73193917-02d77180-4134-11ea-8954-a22833d215f1.png)
### Monkey log:
![image](https://user-images.githubusercontent.com/36815064/73193968-15ea4180-4134-11ea-818a-2bcd1f50bab2.png)

## Expected behaviour
We should test all fields and make sure that empty values either can't be submitter or doesn't end up on configuration.

**Comment by shreyamalviya** [comment]
Hi! I'd like to give this issue a shot. How should I get started?

**Comment by VakarisZ** [comment]
Hi. 1. Take a look at our wiki 2. deploy development environment using deployment scripts. 3. Look at monkey island code, especially configuration service.

**Comment by shreyamalviya** [comment]
Thanks, @VakarisZ. I ran the deployment scripts, but how exactly do I run it and test it?

**Comment by VakarisZ** [comment]
Run mongodb and then island python script. Take a look at scripts in monkey_island/windows or /linux. Scripts there might not be perfect, but they will give you an idea on what to run. You can also install production version, to peek around and see what this project is all about.

**Comment by VakarisZ** [comment]
Also, I've sent you an invite to our slack to the gmail. Join us there to get a better guidance.
