### ISSUE TITLE
Merge install_mongo and deployment scripts

### ISSUE THREAD

**Issue by danielguardicore** [guardicore/monkey#551]
**Is your feature request related to a problem? Please describe.**
Currently installation on Linux is split into two scripts. Deployment and mongo installation. This leads to their configuration files also being split and makes it hard to CR. 

**Describe the solution you'd like**
Single file all the things.

**Comment by danielguardicore** [comment]
@VakarisZ Opened the issue though notice that install_mongo happens as part of the deb installation and not standalone :(

**Comment by ashish493** [comment]
Then to prevent any bugs, I think, we need to write the combined deployment script from scratch...

**Comment by VakarisZ** [comment]
I think it's easier to update broken links and debug when there's a single source of truth. We can keep the installation script split up into different files, but there should only be one config and all scripts should be in the same dir, which is not the case currently.

**Comment by mssalvatore** [comment]
It's been useful to have these scripts separate. Additionally, the configuration has changed, which may have alleviated some of the original concerns.
