### ISSUE TITLE
Not all Monkeys die after telling them to so they have to be killed manually

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#556]
## Describe the bug
After pressing "kill all monkeys" and waiting for a few hours, Monkeys were still scanning and trying to propagate - they had to be killed manually by stopping processes.

Reported by 
 - [ ] TODO add Amit's user

## To Reproduce
1. Configure the Monkey with default settings except for a victim limitation (10)
2. Run the monkey on a full-mesh network with XXX machines
3. Wait until Monkey propagates to at least YYY machines
4. Press "kill all monkeys"
5. wait

 - [x] TODO get network details from Amit

## Expected behavior
All Monkeys have to die within 2 minutes of pressing the "kill all monkeys" button and a clear "killing" progress bar/updates page ought to be created to be able to keep track of which Monkeys were killed successfully.

Mockup of that page: 
After pressing the "Kill all monkeys" button:

| Monkey             	| Kill command sent 	| Dead?                                            	| Last communicated    	|
|--------------------	|-------------------	|--------------------------------------------------	|----------------------	|
| Computer name + IP 	| Yes               	| Yes (good)                                       	| Time (X minutes ago) 	|
| Computer name + IP 	| Yes               	| Collected kill command, waiting for confirmation 	| Time (X minutes ago) 	|
| Computer name + IP 	| Yes               	| Not collected command                            	| Time (X minutes ago) 	|
| Computer name + IP 	| No                	| Other statuses?                                  	| Time (X minutes ago) 	|

## Screenshots/logs
 - [ ] TODO get server logs from Amit

## Machine version (please complete the following information):
 - OS: Windows or Linux
 - [ ] TODO check with Amit

**Comment by CyberTools30001** [comment]
Hi Shay, Regarding the OS:
InfectionMonkey server on Win2012R2
Agents on Win in different versions for example: Win2012R2
All machines are VMs.

**Comment by CyberTools30001** [comment]
btw, didnt see anything related on the log in the UI.
if there any other logs you wish to receive, let me know

**Comment by ShayNehmad** [comment]
Hi @CyberTools30001 , getting the following log files will help us alot in debugging this issue:

* Island log file, which you can download from the Log page of the UI
* Monkey log file, which on Windows can be found at `%temp%\\~df1563.tmp`

**Comment by CyberTools30001** [comment]
**Update**: agent was finally terminated after a couple of hours on a single breached machine
Attached is the island log file
second requested log contains LM-hashes so i cant upload it
[Island_log.txt](https://github.com/guardicore/monkey/files/4796965/Island_log.txt)

**Comment by VakarisZ** [comment]
Closing, because solution to this issue is probably #594
