### ISSUE TITLE
Add pyinstaller build and binary test to CI

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#560]
**Is your feature request related to a problem? Please describe.**
The problem is that pyinstaller might fail sometimes due to hidden imports or mishandled data files, which causes headaches later like #559.

**Describe the solution you'd like**
The CI should try to detect as much of this as possible. 

1. build the pyinstaller using the docker
2. run the output files and see if it throws exceptions

**Describe alternatives you've considered**
Not doing it - probably not too bad since this doesn't happen often.

**Comment by VakarisZ** [comment]
Pyinstaller build could be added, but how do we test the actual binaries? Try to run and see if all imports work?

**Comment by mssalvatore** [comment]
We now build all binaries and packages nightly and run blackbox tests using Jenkins.
