### ISSUE TITLE
Integrate AtomicRedTeam into Monkey and MITRE report

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#571]
**Is your feature request related to a problem? Please describe.**
Increase coverage of MITRE ATT&CK matrix

**Describe the solution you'd like**
Integrate [AtomicRedTeam](https://github.com/redcanaryco/atomic-red-team) into the Monkey and parse the results into our MITRE ATT&CK report.

**Comment by VakarisZ** [comment]
I'm not sure what this integration will achieve. The main time consumer is integrating results/configuration into the monkey and testing. We can easily run the code ourselves by copy pasting atomic red examples.

**Comment by shreyamalviya** [comment]
> We can easily run the code ourselves by copy pasting atomic red examples.

I believe that's what we decided on doing in a discussion about this on Slack.

**Comment by mssalvatore** [comment]
> > We can easily run the code ourselves by copy pasting atomic red examples.
> 
> I believe that's what we decided on doing in a discussion about this on Slack.
