### ISSUE TITLE
Monkey does not stop properly on Ubuntu 16.4 in TD

### ISSUE THREAD

**Issue by ty-box** [guardicore/monkey#578]
When running in TestDrive, Monkey does not stop properly and cannot be restarted.
Workaround: It needs to be killed manually:
- monkey process
- ping process

The ping issue might be related to the TD environment. Via a Zoom we saw that it might be due to the fact that ping is not allowed and not timeout is used on Monkey

Issue noticed on Ubuntu 16.4

**Comment by VakarisZ** [comment]
We added timeouts to various locations (if not solved then reopen) and this issue should be somewhat solved together with #594
