### ISSUE TITLE
Monkey is reported as dead even though it's still running

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#581]
## Describe the bug
When the Monkey is "busy" scanning a big subnet, the Island marks it as dead even though it's still working.

## To Reproduce
1. Configure the Monkey to scan a /16 subnet with actual machines in it
2. Run the monkey 
3. Wait
4. Monkey is marked as dead even though it's still running

## Expected behavior
Shouldn't happen.

## Screenshots
Here's a gif that shows it:
![gif of the bug repro](https://media.giphy.com/media/PmMPaQXJzFzYaPtMLe/giphy.gif)

## Machine version (please complete the following information):
 - OS: Windows, but it doesn't matter.

**Comment by VakarisZ** [comment]
This happens because monkey is deemed dead based on a timeout of communication. We either continue playing "deem dead if ... deam alive if ..." or we implement #594

**Comment by mssalvatore** [comment]
The communication timeout has been removed.
