### ISSUE TITLE
Refactor map generation and report generation backend

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#585]
**Is your feature request related to a problem? Please describe.**
- Report and map generation times are slow
- Monolithic code
- Not testable
- Will solve stuff like #568 

**Describe the solution you'd like**
Improve the code so:
- It's covered with tests
- The data model makes sense
- The report and map generation times are fast even with large amount of nodes and edges

**Describe alternatives you've considered**
Caching as stopgaps, looks like not a good way to solve these issues

**Comment by ShayNehmad** [comment]
Subtasks

- [ ] Profile - make sure that map generation is the issue - few hours
- [ ] Create a test in blackbox for performance - 3 days (depth 1 and fix the fact that the Monkey doesn't scan after reaching depth 0)
- [ ] List which data access patterns we have in the Island - 2-3 days
- [ ] Refactor (intuition - unify node and Monkey, and edge as well - move all to MongoEngine) - 2 weeks

Gut feeling: 3 weeks of work.

**Comment by mssalvatore** [comment]
Something like this might help: https://github.com/robertdavidgraham/masscan

**Comment by VakarisZ** [comment]
@mssalvatore Nice suggestion, but this issue is not about scanning, it's about map and report generation structure, more specifically, how map/report data is stored and later pulled to form map and report.

**Comment by mssalvatore** [comment]
Looks like I posted that into the wrong issue.

**Comment by mssalvatore** [comment]
This has been resolved by #2430, #2334, and previous issues that supported the aforementioned.
