### ISSUE TITLE
Expand list of possible targets according to victims existing connections

### ISSUE THREAD

**Issue by danielguardicore** [guardicore/monkey#589]
**Is your feature request related to a problem? Please describe.**
Currently the Monkey only guesses IPs to scan and doesn't utilize the victims existing connections.
It would be nice if the Monkey would check what existing connections exist that match the target ranges and prioritize them.
**Describe the solution you'd like**
Check existing connections and if something that belongs to target subnets exists, prioritize scanning those IPs.

**Comment by danielguardicore** [comment]
We can do that by looking up the ARP table, checking netstat for existing connections and checking the DNS cache.

**Comment by VakarisZ** [comment]
I did't see your issue and accidentally created a duplicate :/ As The one I created seems more verbose I'm closing this one. Feel free to edit or discuss: https://github.com/guardicore/monkey/issues/592
