### ISSUE TITLE
Add integrations status page to the Monkey

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#605]
To encourage people to use integrations. 
Should look like this:

#### `Product` (logo)
- 🔴 Feature (documentation links)
- 🟢 Feature (documentation links)

E.G.

#### `Guardicore Centra` (logo)
- 🔴 Labeling

#### `AWS` (logo)
- 🔴 SSM
- 🟢 Security Hub

When clicking on an integration it will show the user how to turn it on

Credit to Avishag

**Comment by VakarisZ** [comment]
Where in the actual UI is this done?

**Comment by mssalvatore** [comment]
We are planning to rework the configuration and add a "scenarios" feature  (#673) that will accomplish the same goal.
