### ISSUE TITLE
Endpoints missing jwt protection

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#620]
## Describe the bug
Endpoints on `resources/local_run.py` are missing `@jwt_required()` decorator, thus can be called without authentication.

## Screenshots
![image](https://user-images.githubusercontent.com/36815064/79464092-530ef300-8002-11ea-9f62-bbf61d6acad9.png)

**Comment by ShayNehmad** [comment]
Called by Monkey at any point?

**Comment by VakarisZ** [comment]
Can't find it. Also, doesn't really make sense for monkey to call "run monkey on island" function

**Comment by ShayNehmad** [comment]
True. So let's add auth for these, and also quickly check all the services to make sure that they are protected with auth if they should be?
