### ISSUE TITLE
Automatically validate import paths are from root sources in CI

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#621]
**Is your feature request related to a problem? Please describe.**
The problem: Sometimes IDEs import from sub-packages (`from cc import something` instead of `from monkey_island.cc import something`), and this might not fail in the developer's setup.

**Describe the solution you'd like**
When submitting a PR, go over all the imports in the project and make sure they are one of the following:

- Importing a builtin
- Importing a 3rd party that's covered by the `requirements` files
- Importing something from `common`, `monkey_island`, or `infection_monkey`

**Describe alternatives you've considered**
In the meanwhile, we need to make sure we cover this manually when doing pull requests.

**Comment by VakarisZ** [comment]
If we only use absolute imports the paths, paths they become long and unreadable
