### ISSUE TITLE
UI optimization

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#633]
## Describe the bug
Monkey island downloads `Main.js`, which is 3.5 MB in size and includes a lot of unused data, as old map icons, font awesome icons and other. 

## Expected behavior
UI can be improved by 
a. Downloading only useful data
b. Do asynchronous requests to download page data on separate requests.

## Steps:
Delete old icons

**Comment by acepace** [comment]
We have multiple other low hanging fruits
* Use GZIP compression, either by activating in tornado or switching out tornado with twisted or something else.
* webpack optimization, find duplicated modules, etc.

**Comment by acepace** [comment]
All the old assets are 1100x1100. This doesn't impact main.js size but is just a waste of space.

**Comment by acepace** [comment]
Updating babel brings stuff down to 2.3MiB. I will organize that into a PR as it's very messy.

**Comment by acepace** [comment]
The next step according to Chrome Lighthouse is

- Enabling gzip support server side.
- Adding DNS hint for https://fonts.googleapis.com

The latter is trivial, the former also easy.

**Comment by acepace** [comment]
Done DNS hinting. 
GZIP won't be easy. :(

**Comment by ShayNehmad** [comment]
Is GZip worth it? 
Perhaps preferable to lazyload stuff + cache well?

**Comment by acepace** [comment]
Yes. GZIP >>>>>>>>>> everything else.
Text compresses really really really well. 
GZIP on the weakest setting reduces size by 66%. Standard setting by 71%. Both take 0 CPU time today.

**Comment by acepace** [comment]
@ShayNehmad considering we got this down to 2.4, do you want to close this for now or keep it around to track?

**Comment by mssalvatore** [comment]
The UI is being replaced. Closing this issue.
