### ISSUE TITLE
Document testing

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#638]
**Is your feature request related to a problem? Please describe.**
We should document our testing workflow and do a simple guide on how to run unit tests. 

**Describe the solution you'd like**
We have a wiki entry for testing with instructions on how to 
1. change island configuration for unit test
2. Brief overview of how to interact with mongomock for a unit test (test should extend class `IslandTestCase` etc.) OR link to relevant docs. 
3. Brief overview on how to run all unit tests.

**Comment by ShayNehmad** [comment]
Blocked by #602 as far as I'm concerned - but once #602 is done this is on the docket

**Comment by VakarisZ** [comment]
Documented in the README.md
