### ISSUE TITLE
Monkey doesn't scan different subnetworks

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#648]
## Describe the bug
We need to test monkey's ability to scan different subnetworks

## To Reproduce
1. Configure the Monkey with different subnetworks to scan (with cidr notation)
2. See monkey scanning only the first network ?!?

## Machine version (please complete the following information):
Linux

**Comment by itaymmguardicore** [comment]
Let's add a MonkeyZoo test for it

**Comment by mssalvatore** [comment]
I've configured the monkey like this:

![image](https://user-images.githubusercontent.com/19957806/108734234-41895800-74fd-11eb-82be-b8d99a1102d2.png)

When I run the monkey, I see scans for both subnets:

![648](https://user-images.githubusercontent.com/19957806/108734404-71386000-74fd-11eb-9a7f-8c16b658ca6d.png)

**Comment by VakarisZ** [comment]
If you tested, lets close it and reopen if it re-occurs
