### ISSUE TITLE
Add "Local Job Scheduling" attack technique (T1168)

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#683]
[**T1168**](https://attack.mitre.org/techniques/T1168/)

Job scheduling can be used by adversaries to schedule running malicious code at some specified date and time.

**Adding it as a PBA:**
\- *LINUX*: There are multiple methods supported by Linux for creating pre-scheduled and periodic background jobs.
* _at_: not all systems have `at` so skip this (or check if it exists and then proceed?)  
* _cron_: attempt to add some file with some command (commented) to `/etc/cron.hourly` directory then delete it  

\- *WINDOWS*: not applicable ([T1053](https://attack.mitre.org/techniques/T1053/))

[**Mapping the technique to the ATT&CK matrix**](https://github.com/shreyamalviya/monkey/blob/guide-to-add-attack-technique/monkey/Adding-a-new-attack-technique.md)

**Comment by acepace** [comment]
Cron is pretty much always there, we can rely on it. It also has per user abilities so we don't need to run as root to run it.

**Comment by acepace** [comment]
Why not applicable on windows? We can create scheduled tasks easily from the monkey, just as easily as cron.

**Comment by shreyamalviya** [comment]
> It also has per user abilities so we don't need to run as root to run it.

I can't add files to `/etc/cron.*` without root permissions. I can edit crontab using `crontab -e` but how would I do that in a single command? When we're using `cronab -e`, it creates a temporary copy of the crontab file in `/tmp` which is edited and then runs some checks before installing it to the actual crontab file (see [this](https://askubuntu.com/a/609872)).

About the command to leave, we can just leave in a comment in the file we're editing so nothing will run.

**Comment by acepace** [comment]
Can you explain further? Cron files can exist for per users, I assume there's a command or a file to be created.

**Comment by shreyamalviya** [comment]
Cron files exist per user under `/var/spool/cron/crontab/`. While the file itself is accessible by the user (since the user is the owner), the user doesn't have access to the directory that it is a part of, so the user can't write to the file without root permissions.

But you can use `crontab -e` to edit the file. This creates a temporary copy of `/var/spool/cron/crontab/myusername` in `/tmp` which the user can edit, and before adding the changes to the actual cron file, some checks are run on it.

However, given that using `crontab -e` creates a temporary copy of the cron file to edit, how would we make changes to it using just a command? It creates a file with a random name under `/tmp` which we can't know beforehand.
