### ISSUE TITLE
Telemetry type not displayed in log page

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#689]
## Describe the bug
Monkey telemetry page UI should be improved, because now:
1. Telemetry type is not being displayed

![image](https://user-images.githubusercontent.com/36815064/84898497-0900c700-b0b0-11ea-9f02-c8852fc8ce84.png)

## To Reproduce
Go to map -> monkey telemetry

**Comment by mssalvatore** [comment]
While the type is still missing, the forward/backward buttons are displaying properly for me in both firefox and chromium.
