### ISSUE TITLE
Group all config related source files

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#700]
Move them into `monkey_island/cc/services/configuration`

**Comment by acepace** [comment]
What files for example?

**Comment by ShayNehmad** [comment]
`monkey/monkey_island/cc/services/config.py`
`monkey/monkey_island/cc/services/config_schema.py`
`monkey/monkey_island/cc/services/representations.py`
`monkey/monkey_island/cc/services/representations_test.py`

**Comment by ilija-lazoroski** [comment]
All of the files mentioned are already taken care of.
