### ISSUE TITLE
Replace font awesome CDN files with font awesome icons

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#706]
**Is your feature request related to a problem? Please describe.**
Currently we have font-awesome react and font-awesome CDN, which results in redundant stylesheets.
CDN is required by react-jsonschema-form-bs4 component.

**Describe the solution you'd like**
We should override default array widget for the form and use react font-awesome icons in the custom widget. This would allow us to delete our CDN

**Comment by acepace** [comment]
This makes it easier to use without internet connection, increases installer size, and improves performance.
Anything I'm missing?

**Comment by VakarisZ** [comment]
IIRC `react-jsonschema-form` migrated to bs4 already, so we could go back to core repo.

**Comment by VakarisZ** [comment]
Outdated, the CDN files are long gone
