### ISSUE TITLE
Change outdated react lifecycle methods

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#735]
`componentWillReceiveProps` is deprecated and should be changed to `componentDidUpdate`.
`componentWillMount` also deprecated, should be changed to `componentDidMount`.

**Comment by ShayNehmad** [comment]
Where are we using these? I think these are only in dependencies

**Comment by VakarisZ** [comment]
Closing, due to lack of evidence. If we find other outdated methods, lets reopen
