### ISSUE TITLE
Long post breach action results in security report.

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#742]
## What is this?
Some post breach actions have a long list of outputs/results. We should refactor PBA UI in security report, by adding a UI component, which automatically renders a dropdown component if the number of results is too great. 
## Example of PBA with a lot of output:
![image](https://user-images.githubusercontent.com/36815064/88795873-6147e000-d1a9-11ea-88b8-ceced9b52459.png)

## Expected behaviour:
Differently coloured dropdowns should appear for successful PBA outputs and failed ones.

**Comment by cakekoa** [comment]
PBAs are being removed in #2442
