### ISSUE TITLE
OpenSSL link in deployment scripts is broken

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#750]
## Describe the bug
OpenSSL link for windows in deployment scripts is broken, thus open ssl is not being downloaded and certificate is not being generated

## Screenshots
![image](https://user-images.githubusercontent.com/36815064/89012295-a3446380-d31a-11ea-9d76-069e63a0a0ef.png)

**Comment by mssalvatore** [comment]
This was resolved quite a while ago. We can reopen this if the issue resurfaces.
