### ISSUE TITLE
Island configuration handling refactoring

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#756]
**Is your feature request related to a problem? Please describe.**
`monkey/monkey_island/cc/services/config.py` contains `set_defaults` method, which has hard-coded loops for each layer of configuration object. Code will break if another layer of configuration is introduced.

**Describe the solution you'd like**
Setting island config defaults should be handled in a similar way to `set_arrays` in `monkey/monkey_island/cc/services/attack/attack_config.py` (recursive method that can handle any depth)

**Comment by wrmiller9030** [comment]
Phshing attacks
