### ISSUE TITLE
Profile Monkey execution to see which parts can be parallelized

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#772]
We should profile the Monkey execution and see how long each part takes, so we can consider parallelizing those parts and making execution quicker.

**Comment by VakarisZ** [comment]
For profiling we'll need to gather telemetries and use telem sending test. We also have a profiling decorator. Ideally, we should also document profiling process/move docs to our documentation framework.

**Comment by VakarisZ** [comment]
Either way I don't think we need to parallelize just to parallelize. We should include performance tests into our lifecycle and make issues about specific parts of code that needs improvements, rather than opening issues like "we could improve our performance"
