### ISSUE TITLE
Windows-Dropper does not work properly (python error)

### ISSUE THREAD

**Issue by gituser2k16** [guardicore/monkey#798]
## Describe the bug
The Infection Monkey Windows Dropper doesn't run any Python Collectors neither 32 nor 64bit.

## To Reproduce
1. Deploy Monkey Island on Linux Docker with default settings
2. "Run on a machine of your choice": Windows10 1803 Enterprise machine
3. Nothing happens no network scans at all Monkey Island gets only the Machine Name and thats it

## Expected behavior
Standard Collection with minimal network scan and information harvesting.
On Linux Monkeys everything works as expected.

## Error Message Logs

2020-08-21 12:34:04,932 [16760:16380:INFO] windows_info_collector.get_installed_packages.54: getting installed packages
2020-08-21 12:34:05,129 [16760:16380:ERROR] main.main.137: Exception thrown from monkey's start function. More info: 'charmap' codec can't decode byte 0x81 in position 25: character maps to <undefined>
Traceback (most recent call last):
  File "monkey\infection_monkey\main.py", line 128, in main
  File "monkey\infection_monkey\monkey.py", line 142, in start
  File "monkey\infection_monkey\monkey.py", line 247, in collect_system_info_if_configured
  File "monkey\infection_monkey\system_info\__init__.py", line 46, in get_info
  File "monkey\infection_monkey\system_info\windows_info_collector.py", line 46, in get_info
  File "monkey\infection_monkey\system_info\windows_info_collector.py", line 55, in get_installed_packages
  File "c:\monkey_env\infectionmonkey64\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 25: character maps to <undefined>

After that cleanup is started

## Machine version:
 - OS: Windows10 1803 Enterprise
 - Monkey Versions tested: 1.9.0+192 an 1.8.2

**Comment by gituser2k16** [comment]
Hi @ShayNehmad,

you're right my test Windows is german and so are some of the  installed packages.
I've tried your suggested workaround but with no luck.

1. Disabled Configuration => Monkey => System info collectors
2. Disabled Configuration => ATT&CK => System information discovery (don't know if it matters)
3. Rerun Monkey => Python Error stays the same

Some Screenshots:

The Main Checkbox stays activated after submit
![grafik](https://user-images.githubusercontent.com/20860075/91023266-9e5f9080-e5f6-11ea-8e3b-7cf18c755b38.png)

![grafik](https://user-images.githubusercontent.com/20860075/91023333-b6371480-e5f6-11ea-8983-1c60f7b3be0a.png)

**Comment by ShayNehmad** [comment]
Hi @gituser2k16, 
Thanks for responding. If you run Monkey on the same machine it pulls the OLD configuration. 

Export your current config, "start over" (button under the reports), import the config file you've exported and then try again. It should work. If it doesn't please post the logs here - it might be the same error but from a different part of the Monkey's code...

**Comment by gituser2k16** [comment]
Hi @ShayNehmad,

first of all thanks for your quick replys!

Here's what i've done so far and some more Info about my environment:

- I use the Docker version von Infection Monkey "guardicore/monkey-island:1.9.0" with "mongo/latest"
- then I exported the config with disabled collectors and deployed the containers fresh with new data volume for mongo
- after setting user/pw for the island I imported the config and checked that the collectors are still disabled like in the screenshots
- finaly I ran the monkey on a new windows machine with no former monkey contact

but the result/error stays the same in my eyes

pls find attached the logs and config with only some for me sensitive data redacted

[monkey.log](https://github.com/guardicore/monkey/files/5122683/monkey.log)
[monkey.config.txt](https://github.com/guardicore/monkey/files/5122689/monkey.config.txt)

**Comment by VakarisZ** [comment]
I see multiple issues with this, first of all we should catch exceptions from info_collectors (already taken care of it?). Second issue is the actual bug, which happens in `os.popen("dism /online /get-packages").read()` because `os.popen("dism /online /get-packages")` fails somehow/returns weird data. Maybe this happens when permissions are missing, we need to check
