### ISSUE TITLE
Add a list/table of all supported MITRE techniques 

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#813]
### Edit existing content 📝

**Which page(s) do you want us to edit?**
[The MITRE report documentation page](https://www.guardicore.com/infectionmonkey/docs/usage/reports/mitre/)

**What do you think should be changed?**
Add a list of all supported techniques (with links to MITRE database), perhaps with a summary stat of coverage VS MITRE attack database.

Credit for the suggestion: @ofriz

**Comment by VakarisZ** [comment]
I think config matrix / ATT&CK report should be self-documenting. I'd rather improve our UI to somehow include this information than moving this to documentation hub.

**Comment by shreyamalviya** [comment]
https://www.guardicore.com/infectionmonkey/docs/reference/mitre_techniques/
This was done in #839. 

I think we should open a separate/edit this issue for it being self-documenting?

**Comment by VakarisZ** [comment]
I'm closing this due to what @shreyamalviya pointed out. If the solution is not enough, lets open another, more specific issue
