### ISSUE TITLE
Service missing in monkey report

### ISSUE THREAD

**Issue by stiv-kupchik** [guardicore/monkey#819]
## Describe the bug
Monkey report - segmentation issues
When using ping for machine discovery, the alert line in the report shows "using the services:" with no continuation

## To Reproduce
Configure monkey to attack a machine which blocks all communication besides ICMP

## Expected behavior
I wanted the message line to be "using ICMP/ping" rather than "using services:"
Also, as ping is sometimes accepted/permitted, perhaps move it to a different tier of error/make it configurable - also relevant for ZT I guess

## Screenshots
![image](https://user-images.githubusercontent.com/66255933/91864295-ba0f0a80-ec78-11ea-84a8-2cb5702ede53.png)

## Machine version (please complete the following information):
 - OS: Linux

**Comment by mssalvatore** [comment]
If the monkey was only able to use ICMP, I think "connected to" is not the proper verbiage. Maybe "contacted"?

**Comment by stiv-kupchik** [comment]
perhaps "accessed"?
the bigger issue is the empty services list (I think) - I remember scratching my head for a few minutes trying to understand what went wrong
