### ISSUE TITLE
"run.sh"_not_present

### ISSUE THREAD

**Issue by aoprea1982** [guardicore/monkey#85]
## Expected Behavior
https://github.com/guardicore/monkey/tree/master/monkey_island says => run run.sh (located under /linux) 

## Actual Behavior
There is no  "run.sh" 

## Steps to Reproduce the Problem

 :~/monkey/monkey_island/linux# ls -alh
total 28K
drwxr-xr-x 3 root root 4.0K Feb  8 18:57 .
drwxr-xr-x 6 root root 4.0K Feb  9 20:11 ..
-rw-r--r-- 1 root root  102 Feb  8 18:57 clear_db.sh
-rw-r--r-- 1 root root  303 Feb  8 18:57 create_certificate.sh
-rw-r--r-- 1 root root  265 Feb  8 18:57 install.sh
-rw-r--r-- 1 root root  265 Feb  8 18:57 monkey.sh
drwxr-xr-x 3 root root 4.0K Feb  8 18:57 ubuntu

## Specifications

  - Version: Kali 2018.1
  - Platform: 
  - Subsystem:

**Comment by danielguardicore** [comment]
Fixed, thanks for pointing it out. 

You can git update or just download the file directly [run.sh](https://github.com/guardicore/monkey/blob/8b5e6c30e6f1faee72b181bb0cfcd4b51b8fd1b2/monkey_island/linux/run.sh).
