### ISSUE TITLE
Long imports getting out of hand

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#851]
**Is your feature request related to a problem? Please describe.**
Using absolute imports leads to long import paths which diminish readability. We need to find a good workflow and refactor our import statements.

**Describe the solution you'd like**
Import statements should be no longer than 72 characters

**Comment by VakarisZ** [comment]
Since pyinstaller support local imports, best way to solve this is to structure our code into dedicated packages and use local imports

**Comment by mssalvatore** [comment]
I'm not sure why this is closed? We have a path forward, but until we actually take steps to change the code structure, this is still an issue.

**Comment by VakarisZ** [comment]
The issue was to vague and not really actionable. I don't think long imports are more important than any other kind of formatting issues our codebase suffer. I made this issue, because initially I was unsure that we can do local imports and what's the best way to solve it.
