### ISSUE TITLE
Include "Black" code formatter

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#852]
**Is your feature request related to a problem? Please describe.**
We should include ["Black" code formatter](https://github.com/psf/black) into our CI and workflow. For that, we'll need to first solve #789 

**Describe the solution you'd like**
Travis CI is checking if code is formatted according to "Black". Our validation script automatically formats the code according to "Black".

**Comment by mssalvatore** [comment]
Fixed by 661f3907a9bb46
