### ISSUE TITLE
Island stuck on version update

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#857]
## Describe the bug
If island has no connection to the internet, the version update gets stuck waiting for the timeout and user can't do anything on the island on the meantime. Related #858 

## To Reproduce
1. Run island without internet connection
2. Refresh the island page
3. On each refresh island tries to query for version update and hangs until timeout is reached. Hanging occurs because Tornado WSGI container (as noted in a [warning here](https://www.tornadoweb.org/en/stable/wsgi.html)) is blocking/synchronous server. All other requests doesn't get parsed until version update timeout is reached and execution gets resumed. 

## Expected behavior
Version update process should happen in parallel with other activities on the island.

**Comment by acepace** [comment]
Why not just add a real timeout (say less than 10 seconds)? This is anyway a good practice regardless of gevent.

**Comment by VakarisZ** [comment]
Current timeout is already set (to 15 seconds I think).

**Comment by VakarisZ** [comment]
Hopefully gevent solved this for good

**Comment by mssalvatore** [comment]
> Hopefully gevent solved this for good

Have we run a test to try and reproduce this since the gevent changes?

**Comment by VakarisZ** [comment]
Just checked, it's solved.
