### ISSUE TITLE
SSL warnings

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#859]
## Describe the bug
![image](https://user-images.githubusercontent.com/36815064/95732473-7650ed00-0c89-11eb-8888-ce3fd33474c2.png)

## To Reproduce
1. Configure the Monkey Island on AWS (maybe happens elsewhere too?)

## Expected behavior
Should not be throwing warnings.

## Tasks
- [ ] Fix it! (0.25d) @mssalvatore 

## References
https://stackoverflow.com/questions/66364650/catching-errors-being-thrown-within-module

**Comment by acepace** [comment]
Can't avoid that while using self signed certs. Without control over who's running the island, GC shouldn't sign a blanket cert.

**Comment by VakarisZ** [comment]
I agree with you, but maybe we can ignore/catch the warnings in order not to litter the log and not to confuse users.

**Comment by acepace** [comment]
Ah, hmm.  
This will go away once you use gevent as this warning comes from tornado.

**Comment by mxm0z** [comment]
I'm having the same issue. I even tried with different environments - debian, vmware, docker. All the same. How can I use gevent to fix this? It's not clear

**Comment by VakarisZ** [comment]
@mxm0z You can't but we will on the next release. Also, AFAIK this should not impact your usage of the tool, simply spams the logs.

**Comment by VakarisZ** [comment]
Still happens with gevent, let's try to catch it

**Comment by mssalvatore** [comment]
Since we switched to gevent, the error looks like:
![image](https://user-images.githubusercontent.com/19957806/108863571-55958e00-75bf-11eb-9a53-c71e1e0516e6.png)

**Comment by mssalvatore** [comment]
After spending some time with this, I don't think we should entirely suppress this warning. Since users can now provide their own certificates, this could be useful information for them. 

What we do need is to prevent the traceback from being displayed in the console output. PR #1298 proposes a solution.
