### ISSUE TITLE
Fresh Installation: Not Listening on Port 5000

### ISSUE THREAD

**Issue by ohrekap** [guardicore/monkey#873]
## Describe the bug
Upon fresh installation of Infection Monkey, server appear to not be listening on port 5000

## To Reproduce
1. Configure the Monkey with X settings
2. Run the monkey on specific machine
3. See error

Above steps completed on both Debian and Ubuntu 18.0.4

## Expected behavior
I expected to have just been able to open service on port 5000 in my browser upon installation - according to install guide

## Screenshots
See screenshot/netstat status
![image](https://user-images.githubusercontent.com/46007025/97826046-89564c00-1c8e-11eb-8879-ce3e56695153.png)

`Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      102        32517649   2767/systemd-resolv 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          32553543   18353/sshd          
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      0          32533631   11287/master        
tcp        0      0 0.0.0.0:5001            0.0.0.0:*               LISTEN      0          32594789   28131/python        
tcp6       0      0 :::22                   :::*                    LISTEN      0          32553554   18353/sshd          
tcp6       0      0 ::1:25                  :::*                    LISTEN      0          32533632   11287/master        
udp        0      0 127.0.0.53:53           0.0.0.0:*                           102        32517648   2767/systemd-resolv 
udp6       0      0 fe80::d8c5:48ff:fef:546 :::*                                101        32517582   2762/systemd-networ `
## Machine version (please complete the following information):
 - OS: Linux Ubuntu 18.0.4

**Comment by ohrekap** [comment]
Login came up.

**Comment by WangSongsen** [comment]
Login came up. Can't understand，What did you do?

**Comment by ohrekap** [comment]
I didn't do anything to be honest. The login page was just available the
next morning I tried to check the link to the server.
