### ISSUE TITLE
Monkey Server Configuration

### ISSUE THREAD

**Issue by LogiEx7** [guardicore/monkey#876]
Hello everyone,

I have just discovered the project and it seems very interesting to me. However I would like to install it on a server in the cloud. 
The configuration on port 5000 for the interface and 5001 to receive information does not please me too much.
Is there a possibility to bind to localhost and with an Apache or Nginx virtual host to do the redirection?

Thank you in advance

**Comment by VakarisZ** [comment]
You can do port forwarding or just setup a docker container

**Comment by LogiEx7** [comment]
@VakarisZ Thank you for your answer, but how can I do that?

**Comment by VakarisZ** [comment]
when you setup a docker container, you can map ports in it's configuration. Port forwarding can be achieved in your router configuration. Another option, if you simply don't want to use 5000, I think you can just deploy our VMWare ova. When you deploy it on NAT, port 5000 in VM should be mapped with another IP on the host IIRC.

**Comment by VakarisZ** [comment]
Closing due to incativity. For port configuration we have a separate issue
