### ISSUE TITLE
Bootloader timeout too long

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#884]
## Describe the bug

> From 1.8, the monkey on patient 0 does additional check before spreading in the network. The side effect is that once you « start » the infection, nothing happens on the island map for a good 2 min... which is very bad when demoing IM. No w/a either here apart from being told this must be changed in future versions

This timing is not 2 minutes, but equals to bootloader timeout x 2 . We need to lower bootloader's timeout.

## To Reproduce
1. Run monkey with unreachable island manually
2. See the long timeout

**Comment by VakarisZ** [comment]
More about timeouts https://groups.google.com/g/microsoft.public.inetsdk.programming.wininet/c/Qka9RfpSSRM

**Comment by mssalvatore** [comment]
The bootloader has been removed.
