### ISSUE TITLE
Plugin selector has wrong inital state.

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#891]
## Describe the bug
If you disable all plugins in the config UI, after refreshing plugin selector initiates with a checkmark for checked instead of empty.

![image](https://user-images.githubusercontent.com/36815064/100331396-c507db80-2fd8-11eb-94bb-42ce0d5059b2.png)

## To Reproduce
1. Disable all post breach actions
2. Submit config
3. Refresh page
4. Post breach action checkmark is checked even though none is selected.

## Expected behavior
If no plugins are selected, "check all" checkmark shouldn't be selected

**Comment by mssalvatore** [comment]
This issue also affects "System info collectors".

**Comment by VakarisZ** [comment]
Yes, this bug is in the UI component code, it affects all fields, which are displayed using this component. As this component is reused, you'll only need to solve it in one place - `monkey_island/cc/ui/src/components/ui-components/AdvancedMultiSelect.js`
