### ISSUE TITLE
Unwanted text on Monkey Island in post breach file upload

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#903]
Remove the "Tap to Undo" and "Tap to Cancel" when uploading a file

![tap-to-undo?](https://user-images.githubusercontent.com/44770317/101637147-5ef86b00-3a52-11eb-8099-aeb4210b1382.png)

![tap-to-cancel?](https://user-images.githubusercontent.com/44770317/101637391-b5fe4000-3a52-11eb-8866-6a71abec5c7f.png)

**Comment by VakarisZ** [comment]
Why? How else would you remove the file and upload a different one?

**Comment by shreyamalviya** [comment]
By clicking on the cross and uploading a new one?
The word "tap" is misleading, imo.

**Comment by VakarisZ** [comment]
I think it's because filepond is compatible with mobile. I'm not sure it's worth diving into this api just for that.

**Comment by cakekoa** [comment]
PBAs are being removed in #2442
