### ISSUE TITLE
Remove support for manually uploaded config.

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#906]
## Describe the bug
There is an unmaintained(and probably unused) feature which allows users to provide configuration file path via cmd arguments.
I think this feature is heritage of days long gone and should be removed.

## Changes to code:
1. Remove config argument and related parsing
2. Remove example config file

**Comment by acepace** [comment]
@VakarisZ are you talking about importing config in island or importing config in monkey?

In case of monkey, it is legacy and easy to remove.
However, this is a good mechanism to pass in initial commands to the monkey when it's dropped, besides just the island IP

**Comment by VakarisZ** [comment]
AFAIK there's no cmd arguments for the island. 
What kind on initial commands? Ideally, cmd arguments should only contain info to connect to the island

**Comment by acepace** [comment]
For example, specific tunnel

**Comment by VakarisZ** [comment]
Tunnel is passed via cmd argument, not via config. Monkey either connects to the server and pulls the config or dies and config is not used.  The only use case for manually specifying config is to manually run two monkeys on the network simultaneously with different configs. But until that's a real use case, this "feature" should be removed.

**Comment by acepace** [comment]
Right now it's also broken as the configuration gets overriden by the island anyway so easy deletion.

**Comment by mssalvatore** [comment]
See https://github.com/guardicore/monkey/issues/244 for a use case of this capability.
