### ISSUE TITLE
Conflicting ZeroTrust report (HTTP Servers)

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#908]
## Describe the bug
The Monkey Island's ZeroTrust report gives conflicting (or confusing) results regarding whether or not it found HTTP open servers.

![found_http](https://user-images.githubusercontent.com/19957806/102408082-15140580-3fbb-11eb-8879-4e74f14724ac.png)

...

![found_http_2](https://user-images.githubusercontent.com/19957806/102408095-19d8b980-3fbb-11eb-8017-7d056424bbde.png)

...

![no_http_found](https://user-images.githubusercontent.com/19957806/102408104-1cd3aa00-3fbb-11eb-8918-2dbad6dd8b69.png)

## To Reproduce

Version: commit 44fd1ab69cfbab33cec638dcbbaa8831992a9a9f

1. Configure the Monkey with default settings
2. Configure a webserver to use HTTP
3. Click the "From Island" button on the "Run Monkey" server
4. Wait for scan to complete and view t he ZeroTrust report.

## Machine version (please complete the following information):
 - OS: Ubuntu 18.04

**Comment by VakarisZ** [comment]
Yep, looks like this is the same ZT test. Maybe there's something wrong with parsing? Maybe events where the monkey found open http servers are in one finding and ones where it didn't are in another finding.

**Comment by acepace** [comment]
@VakarisZ how could that happen? Thought they both pulled from the same collection

**Comment by VakarisZ** [comment]
Don't rush fixing this, I might unconciously fix it in ScoutSuite PR

**Comment by mssalvatore** [comment]
The Zero Trust report was removed in #2441.
