### ISSUE TITLE
Steal SSH keys

### ISSUE THREAD

**Issue by itaymmguardicore** [guardicore/monkey#91]
The monkey should steal ssh keys and use them to propagate.

See:
https://mthbernardes.github.io/persistence/2018/01/10/stealing-ssh-credentials.html
https://mthbernardes.github.io/persistence/2018/02/10/stealing-ssh-credentials-another-approach.html

**Comment by danielguardicore** [comment]
Another direction we can take this is steal all the accessible users private SSH keys (anything under /home or /root)

**Comment by danielguardicore** [comment]
Part 1 of this issue is solved in #138
