### ISSUE TITLE
Brief red alert on registration

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#910]
## Describe the bug
When registration is submitted, an empty red alert pops up for a moment:
![image](https://user-images.githubusercontent.com/36815064/102981277-666b4a00-4511-11eb-8bd3-6e2aa0dc335c.png)

## To Reproduce
1. Go to registration screen (reset credentials to trigger it)
2. Enter credentials to register
3. Click on registration
4. See a brief red alert appear

## Expected behavior
Red alert shouldn't appear, since registration is successful.

## Tasks
- [ ] Fix it (0.5d) @ilija-lazoroski

**Comment by mssalvatore** [comment]
@VakarisZ Can you still reproduce this? I am unable to reproduce it in Chromium or Firefox. Is it possible this was caused by a bug in a node.js (or other) dependency that is now fixed?

**Comment by VakarisZ** [comment]
Unable to reproduce either. Closing

**Comment by mssalvatore** [comment]
I am able to reproduce this when selecting "I want anyone to access the island". Reopening.
