### ISSUE TITLE
AWS Security Hub Integration

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#923]
**Describe the solution you'd like**
The AWS security hub collects provides information about the security of AWS instances. Many products push their findings into the AWS security hub, but the security hub can also export the data for consumption by a 3rd party utility. Investigate whether or not it would be interesting for Infection Monkey to consume and display some or all of the AWS security hub's findings.

**Comment by VakarisZ** [comment]
Monkey already pushes it's findings to AWS security hub IIRC
