### ISSUE TITLE
Out of date Zero Trust screenshots

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#939]
### Edit existing content 📝

**Which page(s) do you want us to edit?**
https://www.guardicore.com/infectionmonkey/docs/usage/reports/zero-trust/

**What do you think should be changed?**

The screenshots are outdated. Zero Trust reports are now a sub-report under Security Report.

#### Outdated Screenshot

![](https://www.guardicore.com/infectionmonkey/docs/images/usage/reports/ztreport1.png)

**Comment by shreyamalviya** [comment]
Covered by #2307
