### ISSUE TITLE
Flawless Ubuntu Bionic 18.04 Installation

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#943]
# Spike

## Objective
Test the installation of Infection Monkey on Ubuntu Bionic 18.04. @ilija-lazoroski 

## Scope
The below tests are not intended to be exhaustive. Rather, they are smoke tests to verify the basic functionality of Infection Monkey on Ubuntu Bionic 18.04.

- [ ] Infection monkey installs without errors or warnings.
- [x] Monkey Island starts without errors or warning.
- [x] No additional system changes (dependencies, settings, etc) are required to successfully install and run Monkey Island
- [x] Monkey agent can be started locally
- [x] Monkey agent successfully propagates to a victim machine
- [x] Monkey Island receives telemetry and other expected data from monkey agents

## Output

The output of this spike is a set of GitHub issues (bugs). When these bugs are resolved, we should be able to claim to have a flawless installation experience on Ubuntu Bionic 18.04.

**Comment by mssalvatore** [comment]
Created https://github.com/guardicore/monkey/issues/960

**Comment by ilija-lazoroski** [comment]
AppImage throw similar error as #1355 only this time `libcurl` was missing. Fixed by installing `curl`. We should state pre-requisites for running Infection Monkey.

**Comment by ilija-lazoroski** [comment]
![image](https://user-images.githubusercontent.com/15820737/126957950-c271ab45-29a5-4669-a9de-8f8d987a813f.png)

![image](https://user-images.githubusercontent.com/15820737/126958019-bd6387ba-91b2-417e-92a3-29edc39959fc.png)

![image](https://user-images.githubusercontent.com/15820737/126958056-21a33b6c-65a2-42d0-91e8-315dda1d9f11.png)

**Comment by mssalvatore** [comment]
> AppImage throw similar error as #1355 only this time `libcurl` was missing. Fixed by installing `curl`. We should state pre-requisites for running Infection Monkey.

Instead of listing it as a prerequisite, we should include it in the AppImage. #1362
