### ISSUE TITLE
Flawless Ubuntu Focal 20.04 Installation

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#952]
# Spike

## Objective
Test the installation of Infection Monkey on Ubuntu Focal 20.04.  @mssalvatore 

## Scope
The below tests are not intended to be exhaustive. Rather, they are smoke tests to verify the basic functionality of Infection Monkey on Ubuntu Focal 20.04.

- [x] Infection monkey installs without errors or warnings.
- [x] Monkey Island starts without errors or warning.
- [x] No additional system changes (dependencies, settings, etc) are required to successfully install and run Monkey Island
- [x] Monkey agent can be started locally
- [x] Monkey agent successfully propagates to a victim machine
- [x] Monkey Island receives telemetry and other expected data from monkey agents

## Output

The output of this spike is a set of GitHub issues (bugs). When these bugs are resolved, we should be able to claim to have a flawless installation experience on Ubuntu Focal 20.04.

**Comment by guymatz** [comment]
Getting the following error about python3.7.  Only 3.8 is available:

$ lsb_release  -r
Release:	20.04
$ sudo dpkg -I monkey_island.deb
 new Debian package, version 2.0.
 size 93268660 bytes: control archive=1524 bytes.
     323 bytes,     8 lines   *  control
    2543 bytes,    63 lines   *  postinst             #!/bin/bash
     312 bytes,    10 lines   *  prerm                #!/bin/sh
 Package: gc-monkey-island
 Architecture: amd64
 Maintainer: Guardicore <support@infectionmonkey.com>
 Homepage: https://www.infectionmonkey.com
 Priority: optional
 Version: 1.9.0
 Description: Guardicore Infection Monkey Island installation package
 Depends: openssl, python3.7-dev, python3.7-venv, python3-venv, build-essential
$ sudo dpkg -i ./monkey_island.deb
Selecting previously unselected package gc-monkey-island.
(Reading database ... 179907 files and directories currently installed.)
Preparing to unpack ./monkey_island.deb ...
Unpacking gc-monkey-island (1.9.0) ...
dpkg: dependency problems prevent configuration of gc-monkey-island:
 gc-monkey-island depends on python3.7-dev; however:
  Package python3.7-dev is not installed.
 gc-monkey-island depends on python3.7-venv; however:
  Package python3.7-venv is not installed.

dpkg: error processing package gc-monkey-island (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 gc-monkey-island
$ sudo apt-get install python3.7-venv
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python3.7-venv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3.7-venv' has no installation candidate
$ dpkg -l  | grep python3 | grep venv
ii  python3-venv                               3.8.2-0ubuntu2                      amd64        pyvenv-3 binary for python3 (default python3 version)
ii  python3.8-venv                             3.8.5-1~20.04                       amd64        Interactive high-level object-oriented language (pyvenv binary, version 3.8)

**Comment by mssalvatore** [comment]
Created https://github.com/guardicore/monkey/issues/960

**Comment by mssalvatore** [comment]
AppImage package works on Focal.
