### ISSUE TITLE
Monkey does not scan configured TCP ports

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#956]
## Describe the bug
If a TCP port is added to the TCP scanner's configuration, the monkey island does not configure monkey agents to scan the nfw port.

## To Reproduce
1. Add a new port to the TCP scanner's configuration in the Monkey Island UE
2. Run the monkey
3. Check the monkey's logs and verify that the set of `tcp_target_ports` sent to the monkey from the island does not contain the newly configured port

## Expected behavior
Monkeys should run TCP scans on all configured ports (and only configured ports)

## Screenshots
![image](https://user-images.githubusercontent.com/19957806/106634756-150d9c00-654e-11eb-8722-a8a794a6a2aa.png)

![image (1)](https://user-images.githubusercontent.com/19957806/106634859-340c2e00-654e-11eb-9c43-553c6332fafc.png)

**Comment by VakarisZ** [comment]
IIRC this was due to inproper config handling. This is fixed in scoutsuite!

**Comment by mssalvatore** [comment]
I've confirmed that this issue no longer occurs after https://github.com/guardicore/monkey/pull/848
