### ISSUE TITLE
Document windows installer getting flagged as malware

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#966]
## Documentation request

Since monkey gets flagged as a virus by windows defender once in a while, we need to guide users in what to do if such cases happen (especially likely with old versions).

### Edit existing content 📝
Edit FAQ or Windows installation page to contain information about:

1. How to verify checksum of the installer
2. How to exclude install dir from defender's detection `Add-MpPreference -ExclusionPath "C:\Program Files\Guardicore"`
3. How to proceed with installation (Delete unsuccessful installation files and restart the installation)

**Comment by mssalvatore** [comment]
This has been documented in the FAQ.
