### ISSUE TITLE
ATT&CK report data export

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#979]
There's no way to export ATT&CK techniques from the report.

**Describe the solution you'd like**
User should be able to export at least json format of ATT&CK report data

**Comment by mssalvatore** [comment]
Perhaps something like this would be useful for generating PDF reports.  https://github.com/blacklanternsecurity/writehat

**Comment by VakarisZ** [comment]
Interesting, but I think that generating MD would require significant code additions. It would be easier to export all relevant js,css and HTML and just make our report exportable as an interactive page.

**Comment by VakarisZ** [comment]
ATT&CK report is getting removed in https://github.com/guardicore/monkey/issues/2440
