### ISSUE TITLE
"Credential dumping" disable doesn't remove mimikatz collector

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#982]
## Describe the bug
When I disable "Credential dumping" (T1003), mimikatz and azure collectors don't get disabled in config, even though they are marked with T1003

## To Reproduce
1. Reset the env
2. Go to attack config
3. Disable credential dumping
4. Submit
5. Go to monkey -> system info collectors. Mimikatz collector still enabled

**Comment by mssalvatore** [comment]
The ATTACK configuration screen has been removed.
