### ISSUE TITLE
Option do not include captured/dumped credentials in config export

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#987]
**Is your feature request related to a problem? Please describe.**
When the monkey agent runs on a windows system, it attempts to use mimikatz to dump credentials from memory. These credentials are fed back to the C&C so that other agents can attempt to use them. When a config is exported, it includes these credentials in the export. These credentials may be sensitive.

This may also happen with ssh keys.

**Describe the solution you'd like**
Provide the user with an option to exclude dumped credentials from the configuration file.

**Comment by VakarisZ** [comment]
I think the ideal way would be to use some kind of secret (like user's password) and encrypt the whole config, so it won't be readable. When importing the config, if it's not using the same secret, a secret input prompt could be used. We should also hide password inputs in UI and only have a button option to display them.

**Comment by mssalvatore** [comment]
Resolved by #1204
