### ISSUE TITLE
Add isort to CI

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#990]
**Is your feature request related to a problem? Please describe.**
Isort was running on "fix" mode, we need to add the following line to `travis.yaml` and then fix all issues isort finds.
```
## Check import order
- python -m isort ./monkey --check-only --settings-file ./ci_scripts/isort.cfg
```
This is a prerequisite for #974.

- [x] Create/edit a configuration for isort, make sure isort config is compatible with black config. Ensure travis uses the same configuration. (0d) - @shreyamalviya 
- [x] Edit travis config so that the build fails if isort finds any issues. (0d)
- [x] Reformat all imports with isort (0.25d) - @mssalvatore 
- [x] Run blackbox and unit tests to ensure nothing wonky happened (0d) - @mssalvatore

**Comment by mssalvatore** [comment]
This is a prerequisite for #974.

- [ ] Create a configuration for isort. Ensure travis uses the same configuration. (0.25d)
- [ ] Edit travis config so that the build fails if isort finds any issues. (0.25d)
- [ ] Reformat all imports with isort (0.25d)
- [ ] Run blackbox and unit tests to ensure nothing wonky happened (0.25d)

**Comment by mssalvatore** [comment]
This might be helpful information: https://black.readthedocs.io/en/stable/compatible_configs.html#isort

**Comment by mssalvatore** [comment]
```
$> isort --help
...
  -c, --check-only, --check
                        Checks the file for unsorted / unformatted imports and prints them to the command line without modifying the file. Returns 0 when
                        nothing would change and returns 1 when the file would be reformatted.
...
```
